---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-setec-zeroroot-ai-v1alpha1-sandboxclass
  failurePolicy: Fail
  name: msandboxclass.setec.zeroroot.ai
  rules:
  - apiGroups:
    - setec.zeroroot.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sandboxclasses
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-setec-zeroroot-ai-v1alpha1-sandbox
  failurePolicy: Fail
  name: vsandbox.setec.zeroroot.ai
  rules:
  - apiGroups:
    - setec.zeroroot.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sandboxes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-setec-zeroroot-ai-v1alpha1-sandboxclass
  failurePolicy: Fail
  name: vsandboxclass.setec.zeroroot.ai
  rules:
  - apiGroups:
    - setec.zeroroot.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sandboxclasses
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-setec-zeroroot-ai-v1alpha1-snapshot
  failurePolicy: Fail
  name: vsnapshot.setec.zeroroot.ai
  rules:
  - apiGroups:
    - setec.zeroroot.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - snapshots
  sideEffects: None
