---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
  verbs:
  - get
  - list
- apiGroups:
  - setec.zeroroot.ai
  resources:
  - sandboxclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - setec.zeroroot.ai
  resources:
  - sandboxes
  - snapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - setec.zeroroot.ai
  resources:
  - sandboxes/finalizers
  - snapshots/finalizers
  verbs:
  - update
- apiGroups:
  - setec.zeroroot.ai
  resources:
  - sandboxes/status
  - snapshots/status
  verbs:
  - get
  - patch
  - update
