# This rule is not used by the project setec itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to setec.setec.zeroroot.ai resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: setec
    app.kubernetes.io/managed-by: kustomize
  name: sandbox-viewer-role
rules:
- apiGroups:
  - setec.setec.zeroroot.ai
  resources:
  - sandboxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - setec.setec.zeroroot.ai
  resources:
  - sandboxes/status
  verbs:
  - get
