{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "setec.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "setec.labels" . | nindent 4 }}
{{- end -}}
