// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Zero Root AI

package netpol

import (
	networkingv1 "k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BaselineName is the fixed name of the namespace-wide baseline policy.
// One object per namespace, independent of how many Sandboxes run there.
const BaselineName = "setec-sandbox-baseline-deny"

// BaselineManagedByLabel marks the baseline policy as operator-managed so
// it is distinguishable from a hand-written policy of the same name.
const BaselineManagedByLabel = "setec.zeroroot.ai/managed-by"

// BaselineManagedByValue is the value of BaselineManagedByLabel.
const BaselineManagedByValue = "setec-operator"

// NamespaceBaseline returns the namespace-wide default-deny policy for a
// namespace that hosts Sandbox Pods.
//
// # WHY THIS IS NOT THE PER-SANDBOX POLICY
//
// Every policy generated by Generate selects on the
// setec.zeroroot.ai/sandbox label, whose value is the Sandbox name. That
// binds the posture to Pods the operator built from a Sandbox object. A
// Pod created some other way — by hand, by a controller, by anything that
// can write a Pod into this namespace — carries no such label, is
// therefore selected by no policy, and in Kubernetes an unselected Pod is
// unrestricted, not denied. Label-scoped confinement only ever confines
// workloads that cooperate by wearing the label.
//
// This policy selects podSelector: {} — every Pod in the namespace,
// present and future, whatever it is labelled. It lists both policy types
// with no rules, which is the NetworkPolicy spelling of deny-all. Because
// NetworkPolicies union, it subtracts nothing from a Sandbox that has its
// own policy: a Sandbox under external-only still reaches the internet.
// What it removes is the unselected state itself.
//
// # WHY THERE IS NO LABEL-BASED EXEMPTION
//
// A namespace listed for baseline treatment is a Sandbox-only namespace.
// Deliberately, no "exempt these Pods" selector is offered: any label an
// exempt Pod could wear, a Pod written by an adversary could wear too,
// which is the exact failure this policy exists to remove. Infrastructure
// that needs ordinary egress belongs in a different namespace.
func NamespaceBaseline(namespace string) *networkingv1.NetworkPolicy {
	return &networkingv1.NetworkPolicy{
		ObjectMeta: metav1.ObjectMeta{
			Name:      BaselineName,
			Namespace: namespace,
			Labels: map[string]string{
				BaselineManagedByLabel: BaselineManagedByValue,
			},
		},
		Spec: networkingv1.NetworkPolicySpec{
			// Empty selector: every Pod in the namespace.
			PodSelector: metav1.LabelSelector{},
			PolicyTypes: bothDirections(),
		},
	}
}

// BaselineIsIntact reports whether an existing policy still expresses the
// namespace-wide deny. It is false when the selector has been narrowed
// away from "every Pod", when either direction has been dropped from
// policyTypes, or when any rule has been added — each of which turns the
// object back into an allow for some population.
//
// The controller uses this to decide whether to reconcile the object back
// to the baseline shape rather than trusting the name alone.
func BaselineIsIntact(np *networkingv1.NetworkPolicy) bool {
	if np == nil {
		return false
	}
	if len(np.Spec.PodSelector.MatchLabels) != 0 || len(np.Spec.PodSelector.MatchExpressions) != 0 {
		return false
	}
	if len(np.Spec.Ingress) != 0 || len(np.Spec.Egress) != 0 {
		return false
	}
	var hasIngress, hasEgress bool
	for _, t := range np.Spec.PolicyTypes {
		switch t {
		case networkingv1.PolicyTypeIngress:
			hasIngress = true
		case networkingv1.PolicyTypeEgress:
			hasEgress = true
		}
	}
	return hasIngress && hasEgress
}
