// Copyright 2026 The Setec Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/grpc/v1/lease.proto

package setecv1grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeaseService_Lease_FullMethodName      = "/setec.v1.LeaseService/Lease"
	LeaseService_Exec_FullMethodName       = "/setec.v1.LeaseService/Exec"
	LeaseService_Release_FullMethodName    = "/setec.v1.LeaseService/Release"
	LeaseService_PoolStatus_FullMethodName = "/setec.v1.LeaseService/PoolStatus"
)

// LeaseServiceClient is the client API for LeaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LeaseService is the warm-pool lease layer over SandboxService. Where
// SandboxService.Launch cold-boots a fresh Sandbox per call, LeaseService
// keeps a pool of pre-warmed Sandboxes per SandboxClass (restored from a
// Snapshot when the class declares one) so a caller can claim one without
// paying cold-boot latency.
//
// The contract is Lease -> Exec -> Release:
//   - Lease claims a pre-warmed Sandbox from the pool for a class. Fast:
//     no cold boot, because the Sandbox is already Running.
//   - Exec runs a command inside the leased Sandbox (one execution per
//     lease) and streams its output.
//   - Release destroys the leased Sandbox (destroy-on-release — a dirty
//     sandbox is never handed to another caller) and replenishes the pool
//     back to its warm target.
//
// Like SandboxService this is tenant-scoped via mTLS client certificate
// and carries NO datastore or zeroroot-platform coupling (ADR-0056). It is
// an additive surface layered on the v1 isolation ABI; the WIRE breaking
// gate guards its wire stability the same way it guards SandboxService.
type LeaseServiceClient interface {
	// Lease claims a pre-warmed Sandbox from the pool for the requested
	// SandboxClass and returns a lease the caller uses for Exec and Release.
	// If the pool is empty the call cold-launches a Sandbox on demand (and
	// the replenish loop refills the pool in the background) unless the
	// request sets fail_if_empty.
	Lease(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (*LeaseResponse, error)
	// Exec runs a command inside the leased Sandbox and streams stdout/stderr
	// until the command exits. Exactly one Exec may run per lease; a second
	// Exec on the same lease returns FailedPrecondition.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecResponse], error)
	// Release destroys the leased Sandbox (destroy-on-release) and triggers
	// a pool replenish. Releasing an unknown or already-released lease is a
	// no-op success so clients can call it idempotently in cleanup paths.
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	// PoolStatus reports the warm fill level for a SandboxClass: how many
	// Sandboxes are ready to lease versus the configured target.
	PoolStatus(ctx context.Context, in *PoolStatusRequest, opts ...grpc.CallOption) (*PoolStatusResponse, error)
}

type leaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaseServiceClient(cc grpc.ClientConnInterface) LeaseServiceClient {
	return &leaseServiceClient{cc}
}

func (c *leaseServiceClient) Lease(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (*LeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaseResponse)
	err := c.cc.Invoke(ctx, LeaseService_Lease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LeaseService_ServiceDesc.Streams[0], LeaseService_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeaseService_ExecClient = grpc.ServerStreamingClient[ExecResponse]

func (c *leaseServiceClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, LeaseService_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseServiceClient) PoolStatus(ctx context.Context, in *PoolStatusRequest, opts ...grpc.CallOption) (*PoolStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoolStatusResponse)
	err := c.cc.Invoke(ctx, LeaseService_PoolStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaseServiceServer is the server API for LeaseService service.
// All implementations must embed UnimplementedLeaseServiceServer
// for forward compatibility.
//
// LeaseService is the warm-pool lease layer over SandboxService. Where
// SandboxService.Launch cold-boots a fresh Sandbox per call, LeaseService
// keeps a pool of pre-warmed Sandboxes per SandboxClass (restored from a
// Snapshot when the class declares one) so a caller can claim one without
// paying cold-boot latency.
//
// The contract is Lease -> Exec -> Release:
//   - Lease claims a pre-warmed Sandbox from the pool for a class. Fast:
//     no cold boot, because the Sandbox is already Running.
//   - Exec runs a command inside the leased Sandbox (one execution per
//     lease) and streams its output.
//   - Release destroys the leased Sandbox (destroy-on-release — a dirty
//     sandbox is never handed to another caller) and replenishes the pool
//     back to its warm target.
//
// Like SandboxService this is tenant-scoped via mTLS client certificate
// and carries NO datastore or zeroroot-platform coupling (ADR-0056). It is
// an additive surface layered on the v1 isolation ABI; the WIRE breaking
// gate guards its wire stability the same way it guards SandboxService.
type LeaseServiceServer interface {
	// Lease claims a pre-warmed Sandbox from the pool for the requested
	// SandboxClass and returns a lease the caller uses for Exec and Release.
	// If the pool is empty the call cold-launches a Sandbox on demand (and
	// the replenish loop refills the pool in the background) unless the
	// request sets fail_if_empty.
	Lease(context.Context, *LeaseRequest) (*LeaseResponse, error)
	// Exec runs a command inside the leased Sandbox and streams stdout/stderr
	// until the command exits. Exactly one Exec may run per lease; a second
	// Exec on the same lease returns FailedPrecondition.
	Exec(*ExecRequest, grpc.ServerStreamingServer[ExecResponse]) error
	// Release destroys the leased Sandbox (destroy-on-release) and triggers
	// a pool replenish. Releasing an unknown or already-released lease is a
	// no-op success so clients can call it idempotently in cleanup paths.
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	// PoolStatus reports the warm fill level for a SandboxClass: how many
	// Sandboxes are ready to lease versus the configured target.
	PoolStatus(context.Context, *PoolStatusRequest) (*PoolStatusResponse, error)
	mustEmbedUnimplementedLeaseServiceServer()
}

// UnimplementedLeaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaseServiceServer struct{}

func (UnimplementedLeaseServiceServer) Lease(context.Context, *LeaseRequest) (*LeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lease not implemented")
}
func (UnimplementedLeaseServiceServer) Exec(*ExecRequest, grpc.ServerStreamingServer[ExecResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedLeaseServiceServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedLeaseServiceServer) PoolStatus(context.Context, *PoolStatusRequest) (*PoolStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PoolStatus not implemented")
}
func (UnimplementedLeaseServiceServer) mustEmbedUnimplementedLeaseServiceServer() {}
func (UnimplementedLeaseServiceServer) testEmbeddedByValue()                      {}

// UnsafeLeaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaseServiceServer will
// result in compilation errors.
type UnsafeLeaseServiceServer interface {
	mustEmbedUnimplementedLeaseServiceServer()
}

func RegisterLeaseServiceServer(s grpc.ServiceRegistrar, srv LeaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedLeaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeaseService_ServiceDesc, srv)
}

func _LeaseService_Lease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServiceServer).Lease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseService_Lease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServiceServer).Lease(ctx, req.(*LeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LeaseServiceServer).Exec(m, &grpc.GenericServerStream[ExecRequest, ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeaseService_ExecServer = grpc.ServerStreamingServer[ExecResponse]

func _LeaseService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseService_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServiceServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseService_PoolStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServiceServer).PoolStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseService_PoolStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServiceServer).PoolStatus(ctx, req.(*PoolStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeaseService_ServiceDesc is the grpc.ServiceDesc for LeaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "setec.v1.LeaseService",
	HandlerType: (*LeaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lease",
			Handler:    _LeaseService_Lease_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _LeaseService_Release_Handler,
		},
		{
			MethodName: "PoolStatus",
			Handler:    _LeaseService_PoolStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _LeaseService_Exec_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/grpc/v1/lease.proto",
}
