// Copyright 2026 The Setec Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: api/grpc/v1/lease.proto

package setecv1grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LeaseRequest selects the pool to claim from.
type LeaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the cluster-scoped SandboxClass whose pool to lease from.
	// The pool for a class is identified by this name; a class without a
	// registered pool is lazily registered with the cluster-default warm
	// target on first Lease.
	SandboxClass string `protobuf:"bytes,1,opt,name=sandbox_class,json=sandboxClass,proto3" json:"sandbox_class,omitempty"`
	// fail_if_empty, when true, returns ResourceExhausted instead of
	// cold-launching when the pool has no ready Sandbox. Useful for callers
	// that only ever want the fast path.
	FailIfEmpty   bool `protobuf:"varint,2,opt,name=fail_if_empty,json=failIfEmpty,proto3" json:"fail_if_empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRequest) Reset() {
	*x = LeaseRequest{}
	mi := &file_api_grpc_v1_lease_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRequest) ProtoMessage() {}

func (x *LeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_lease_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRequest.ProtoReflect.Descriptor instead.
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_lease_proto_rawDescGZIP(), []int{0}
}

func (x *LeaseRequest) GetSandboxClass() string {
	if x != nil {
		return x.SandboxClass
	}
	return ""
}

func (x *LeaseRequest) GetFailIfEmpty() bool {
	if x != nil {
		return x.FailIfEmpty
	}
	return false
}

// LeaseResponse identifies the claimed Sandbox and the lease over it.
type LeaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lease_id is an opaque token scoped to the caller's tenant. Pass it to
	// Exec and Release.
	LeaseId string `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// sandbox_id is the <namespace>/<name>/<uid> tuple of the leased
	// Sandbox, identical in shape to SandboxService ids so callers may also
	// drive it through SandboxService (e.g. StreamLogs) if they wish.
	SandboxId string `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// warm is true when the lease was satisfied from a pre-warmed pool entry
	// (the fast path) and false when it was cold-launched on demand.
	Warm          bool `protobuf:"varint,3,opt,name=warm,proto3" json:"warm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseResponse) Reset() {
	*x = LeaseResponse{}
	mi := &file_api_grpc_v1_lease_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseResponse) ProtoMessage() {}

func (x *LeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_lease_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseResponse.ProtoReflect.Descriptor instead.
func (*LeaseResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_lease_proto_rawDescGZIP(), []int{1}
}

func (x *LeaseResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LeaseResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *LeaseResponse) GetWarm() bool {
	if x != nil {
		return x.Warm
	}
	return false
}

// ExecRequest runs a command inside a leased Sandbox.
type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lease_id returned by Lease.
	LeaseId string `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// command is the entrypoint to execute inside the leased Sandbox. At
	// least one entry required.
	Command []string `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	// env overlays environment variables for this execution. Optional.
	Env           map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_api_grpc_v1_lease_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_lease_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_lease_proto_rawDescGZIP(), []int{2}
}

func (x *ExecRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ExecRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// ExecResponse is a single chunk of the executing command's output, or
// the final terminal outcome when `done` is set.
type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data is a chunk of stdout/stderr output. Empty on the final message.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// stream is "stdout" or "stderr" for output chunks.
	Stream string `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	// done is set on the final message of the stream. When done is true,
	// exit_code and reason carry the terminal outcome.
	Done          bool   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	ExitCode      int32  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_api_grpc_v1_lease_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_lease_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_lease_proto_rawDescGZIP(), []int{3}
}

func (x *ExecResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecResponse) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *ExecResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ReleaseRequest releases a lease and destroys its Sandbox.
type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_api_grpc_v1_lease_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_lease_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_lease_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

// ReleaseResponse is currently empty; failures surface via gRPC status.
type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_api_grpc_v1_lease_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_lease_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_lease_proto_rawDescGZIP(), []int{5}
}

// PoolStatusRequest selects a class's pool.
type PoolStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxClass  string                 `protobuf:"bytes,1,opt,name=sandbox_class,json=sandboxClass,proto3" json:"sandbox_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolStatusRequest) Reset() {
	*x = PoolStatusRequest{}
	mi := &file_api_grpc_v1_lease_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolStatusRequest) ProtoMessage() {}

func (x *PoolStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_lease_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolStatusRequest.ProtoReflect.Descriptor instead.
func (*PoolStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_lease_proto_rawDescGZIP(), []int{6}
}

func (x *PoolStatusRequest) GetSandboxClass() string {
	if x != nil {
		return x.SandboxClass
	}
	return ""
}

// PoolStatusResponse reports the warm fill level for a class.
type PoolStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ready is the number of pre-warmed Sandboxes currently available to
	// lease without a cold boot.
	Ready uint32 `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// target is the configured warm-pool size for the class.
	Target uint32 `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`
	// leased is the number of Sandboxes currently checked out via Lease and
	// not yet Released.
	Leased        uint32 `protobuf:"varint,3,opt,name=leased,proto3" json:"leased,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolStatusResponse) Reset() {
	*x = PoolStatusResponse{}
	mi := &file_api_grpc_v1_lease_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolStatusResponse) ProtoMessage() {}

func (x *PoolStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_lease_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolStatusResponse.ProtoReflect.Descriptor instead.
func (*PoolStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_lease_proto_rawDescGZIP(), []int{7}
}

func (x *PoolStatusResponse) GetReady() uint32 {
	if x != nil {
		return x.Ready
	}
	return 0
}

func (x *PoolStatusResponse) GetTarget() uint32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *PoolStatusResponse) GetLeased() uint32 {
	if x != nil {
		return x.Leased
	}
	return 0
}

var File_api_grpc_v1_lease_proto protoreflect.FileDescriptor

var file_api_grpc_v1_lease_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x74, 0x65, 0x63,
	0x2e, 0x76, 0x31, 0x22, 0x57, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x66, 0x61, 0x69, 0x6c,
	0x5f, 0x69, 0x66, 0x5f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x66, 0x61, 0x69, 0x6c, 0x49, 0x66, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x5d, 0x0a, 0x0d,
	0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x61, 0x72, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x77, 0x61, 0x72, 0x6d, 0x22, 0xac, 0x01, 0x0a, 0x0b,
	0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x30, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x65,
	0x6e, 0x76, 0x1a, 0x36, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x83, 0x01, 0x0a, 0x0c, 0x45,
	0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x22, 0x2b, 0x0a, 0x0e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x22, 0x11, 0x0a,
	0x0f, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x38, 0x0a, 0x11, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x22, 0x5a, 0x0a, 0x12, 0x50, 0x6f,
	0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x32, 0x8a, 0x02, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x73, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x4c, 0x65, 0x61, 0x73, 0x65,
	0x12, 0x16, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x37, 0x0a, 0x04, 0x45, 0x78, 0x65, 0x63, 0x12, 0x15, 0x2e, 0x73, 0x65, 0x74, 0x65,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x3e, 0x0a, 0x07, 0x52, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x18, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x50, 0x6f,
	0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x7a, 0x65, 0x72, 0x6f, 0x72, 0x6f, 0x6f, 0x74, 0x2d, 0x61, 0x69, 0x2f, 0x73, 0x65,
	0x74, 0x65, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x3b,
	0x73, 0x65, 0x74, 0x65, 0x63, 0x76, 0x31, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_api_grpc_v1_lease_proto_rawDescOnce sync.Once
	file_api_grpc_v1_lease_proto_rawDescData []byte
)

func file_api_grpc_v1_lease_proto_rawDescGZIP() []byte {
	file_api_grpc_v1_lease_proto_rawDescOnce.Do(func() {
		file_api_grpc_v1_lease_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_v1_lease_proto_rawDesc), len(file_api_grpc_v1_lease_proto_rawDesc)))
	})
	return file_api_grpc_v1_lease_proto_rawDescData
}

var file_api_grpc_v1_lease_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_grpc_v1_lease_proto_goTypes = []any{
	(*LeaseRequest)(nil),       // 0: setec.v1.LeaseRequest
	(*LeaseResponse)(nil),      // 1: setec.v1.LeaseResponse
	(*ExecRequest)(nil),        // 2: setec.v1.ExecRequest
	(*ExecResponse)(nil),       // 3: setec.v1.ExecResponse
	(*ReleaseRequest)(nil),     // 4: setec.v1.ReleaseRequest
	(*ReleaseResponse)(nil),    // 5: setec.v1.ReleaseResponse
	(*PoolStatusRequest)(nil),  // 6: setec.v1.PoolStatusRequest
	(*PoolStatusResponse)(nil), // 7: setec.v1.PoolStatusResponse
	nil,                        // 8: setec.v1.ExecRequest.EnvEntry
}
var file_api_grpc_v1_lease_proto_depIdxs = []int32{
	8, // 0: setec.v1.ExecRequest.env:type_name -> setec.v1.ExecRequest.EnvEntry
	0, // 1: setec.v1.LeaseService.Lease:input_type -> setec.v1.LeaseRequest
	2, // 2: setec.v1.LeaseService.Exec:input_type -> setec.v1.ExecRequest
	4, // 3: setec.v1.LeaseService.Release:input_type -> setec.v1.ReleaseRequest
	6, // 4: setec.v1.LeaseService.PoolStatus:input_type -> setec.v1.PoolStatusRequest
	1, // 5: setec.v1.LeaseService.Lease:output_type -> setec.v1.LeaseResponse
	3, // 6: setec.v1.LeaseService.Exec:output_type -> setec.v1.ExecResponse
	5, // 7: setec.v1.LeaseService.Release:output_type -> setec.v1.ReleaseResponse
	7, // 8: setec.v1.LeaseService.PoolStatus:output_type -> setec.v1.PoolStatusResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_grpc_v1_lease_proto_init() }
func file_api_grpc_v1_lease_proto_init() {
	if File_api_grpc_v1_lease_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_v1_lease_proto_rawDesc), len(file_api_grpc_v1_lease_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_v1_lease_proto_goTypes,
		DependencyIndexes: file_api_grpc_v1_lease_proto_depIdxs,
		MessageInfos:      file_api_grpc_v1_lease_proto_msgTypes,
	}.Build()
	File_api_grpc_v1_lease_proto = out.File
	file_api_grpc_v1_lease_proto_goTypes = nil
	file_api_grpc_v1_lease_proto_depIdxs = nil
}
