// Copyright 2026 The Setec Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/grpc/v1/nodeagent.proto

package setecv1grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeAgentService_CreateSnapshot_FullMethodName = "/setec.v1.NodeAgentService/CreateSnapshot"
	NodeAgentService_RestoreSandbox_FullMethodName = "/setec.v1.NodeAgentService/RestoreSandbox"
	NodeAgentService_PauseSandbox_FullMethodName   = "/setec.v1.NodeAgentService/PauseSandbox"
	NodeAgentService_ResumeSandbox_FullMethodName  = "/setec.v1.NodeAgentService/ResumeSandbox"
	NodeAgentService_QueryPool_FullMethodName      = "/setec.v1.NodeAgentService/QueryPool"
	NodeAgentService_DeleteSnapshot_FullMethodName = "/setec.v1.NodeAgentService/DeleteSnapshot"
)

// NodeAgentServiceClient is the client API for NodeAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeAgentService is the internal gRPC surface the Setec operator
// calls on each node-agent DaemonSet pod to drive snapshot, restore,
// pause, and resume operations synchronously. It is NEVER exposed
// outside the cluster; authentication is mTLS with a shared CA
// provisioned at chart install time.
type NodeAgentServiceClient interface {
	// CreateSnapshot pauses the target microVM, persists its state
	// (CPU + memory) via the configured storage backend, and returns
	// the resulting storage reference and digest. The node-agent
	// resumes the VM locally unless the caller sends a subsequent
	// PauseSandbox (the Coordinator decides based on
	// Sandbox.spec.snapshot.afterCreate).
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	// RestoreSandbox loads a previously-persisted snapshot into a new
	// Firecracker microVM attached to the caller-provided Kata socket.
	// Called after the Pod has been scheduled and Kata has set up the
	// surrounding sandbox container.
	RestoreSandbox(ctx context.Context, in *RestoreSandboxRequest, opts ...grpc.CallOption) (*RestoreSandboxResponse, error)
	// PauseSandbox issues the Firecracker PATCH /vm state=Paused call
	// against the target microVM without persisting state.
	PauseSandbox(ctx context.Context, in *PauseSandboxRequest, opts ...grpc.CallOption) (*PauseSandboxResponse, error)
	// ResumeSandbox is the inverse of PauseSandbox.
	ResumeSandbox(ctx context.Context, in *ResumeSandboxRequest, opts ...grpc.CallOption) (*ResumeSandboxResponse, error)
	// QueryPool returns the current set of pre-warmed pool entries the
	// node has available for the given SandboxClass. The operator uses
	// this to pick a pool-hosting node at scheduling time. Empty result
	// means the operator falls back to cold boot.
	QueryPool(ctx context.Context, in *QueryPoolRequest, opts ...grpc.CallOption) (*QueryPoolResponse, error)
	// DeleteSnapshot securely erases the persisted state files and
	// returns success. Called by the SnapshotReconciler when a
	// Snapshot CR is being deleted (TTL elapsed, user kubectl
	// delete, or namespace teardown).
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
}

type nodeAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAgentServiceClient(cc grpc.ClientConnInterface) NodeAgentServiceClient {
	return &nodeAgentServiceClient{cc}
}

func (c *nodeAgentServiceClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) RestoreSandbox(ctx context.Context, in *RestoreSandboxRequest, opts ...grpc.CallOption) (*RestoreSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreSandboxResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_RestoreSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) PauseSandbox(ctx context.Context, in *PauseSandboxRequest, opts ...grpc.CallOption) (*PauseSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseSandboxResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_PauseSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) ResumeSandbox(ctx context.Context, in *ResumeSandboxRequest, opts ...grpc.CallOption) (*ResumeSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeSandboxResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_ResumeSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) QueryPool(ctx context.Context, in *QueryPoolRequest, opts ...grpc.CallOption) (*QueryPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPoolResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_QueryPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeAgentServiceServer is the server API for NodeAgentService service.
// All implementations must embed UnimplementedNodeAgentServiceServer
// for forward compatibility.
//
// NodeAgentService is the internal gRPC surface the Setec operator
// calls on each node-agent DaemonSet pod to drive snapshot, restore,
// pause, and resume operations synchronously. It is NEVER exposed
// outside the cluster; authentication is mTLS with a shared CA
// provisioned at chart install time.
type NodeAgentServiceServer interface {
	// CreateSnapshot pauses the target microVM, persists its state
	// (CPU + memory) via the configured storage backend, and returns
	// the resulting storage reference and digest. The node-agent
	// resumes the VM locally unless the caller sends a subsequent
	// PauseSandbox (the Coordinator decides based on
	// Sandbox.spec.snapshot.afterCreate).
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	// RestoreSandbox loads a previously-persisted snapshot into a new
	// Firecracker microVM attached to the caller-provided Kata socket.
	// Called after the Pod has been scheduled and Kata has set up the
	// surrounding sandbox container.
	RestoreSandbox(context.Context, *RestoreSandboxRequest) (*RestoreSandboxResponse, error)
	// PauseSandbox issues the Firecracker PATCH /vm state=Paused call
	// against the target microVM without persisting state.
	PauseSandbox(context.Context, *PauseSandboxRequest) (*PauseSandboxResponse, error)
	// ResumeSandbox is the inverse of PauseSandbox.
	ResumeSandbox(context.Context, *ResumeSandboxRequest) (*ResumeSandboxResponse, error)
	// QueryPool returns the current set of pre-warmed pool entries the
	// node has available for the given SandboxClass. The operator uses
	// this to pick a pool-hosting node at scheduling time. Empty result
	// means the operator falls back to cold boot.
	QueryPool(context.Context, *QueryPoolRequest) (*QueryPoolResponse, error)
	// DeleteSnapshot securely erases the persisted state files and
	// returns success. Called by the SnapshotReconciler when a
	// Snapshot CR is being deleted (TTL elapsed, user kubectl
	// delete, or namespace teardown).
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	mustEmbedUnimplementedNodeAgentServiceServer()
}

// UnimplementedNodeAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeAgentServiceServer struct{}

func (UnimplementedNodeAgentServiceServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedNodeAgentServiceServer) RestoreSandbox(context.Context, *RestoreSandboxRequest) (*RestoreSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreSandbox not implemented")
}
func (UnimplementedNodeAgentServiceServer) PauseSandbox(context.Context, *PauseSandboxRequest) (*PauseSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseSandbox not implemented")
}
func (UnimplementedNodeAgentServiceServer) ResumeSandbox(context.Context, *ResumeSandboxRequest) (*ResumeSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeSandbox not implemented")
}
func (UnimplementedNodeAgentServiceServer) QueryPool(context.Context, *QueryPoolRequest) (*QueryPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryPool not implemented")
}
func (UnimplementedNodeAgentServiceServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedNodeAgentServiceServer) mustEmbedUnimplementedNodeAgentServiceServer() {}
func (UnimplementedNodeAgentServiceServer) testEmbeddedByValue()                          {}

// UnsafeNodeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAgentServiceServer will
// result in compilation errors.
type UnsafeNodeAgentServiceServer interface {
	mustEmbedUnimplementedNodeAgentServiceServer()
}

func RegisterNodeAgentServiceServer(s grpc.ServiceRegistrar, srv NodeAgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeAgentService_ServiceDesc, srv)
}

func _NodeAgentService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_RestoreSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).RestoreSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_RestoreSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).RestoreSandbox(ctx, req.(*RestoreSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_PauseSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).PauseSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_PauseSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).PauseSandbox(ctx, req.(*PauseSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_ResumeSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).ResumeSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_ResumeSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).ResumeSandbox(ctx, req.(*ResumeSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_QueryPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).QueryPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_QueryPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).QueryPool(ctx, req.(*QueryPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeAgentService_ServiceDesc is the grpc.ServiceDesc for NodeAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "setec.v1.NodeAgentService",
	HandlerType: (*NodeAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSnapshot",
			Handler:    _NodeAgentService_CreateSnapshot_Handler,
		},
		{
			MethodName: "RestoreSandbox",
			Handler:    _NodeAgentService_RestoreSandbox_Handler,
		},
		{
			MethodName: "PauseSandbox",
			Handler:    _NodeAgentService_PauseSandbox_Handler,
		},
		{
			MethodName: "ResumeSandbox",
			Handler:    _NodeAgentService_ResumeSandbox_Handler,
		},
		{
			MethodName: "QueryPool",
			Handler:    _NodeAgentService_QueryPool_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _NodeAgentService_DeleteSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/v1/nodeagent.proto",
}
