// Copyright 2026 The Setec Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: api/grpc/v1/nodeagent.proto

package setecv1grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateSnapshotRequest identifies the sandbox to snapshot and where
// the resulting state should be written.
type CreateSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sandbox_id is the composite <namespace>/<name>/<uid> tuple used
	// elsewhere in the Setec API. Present primarily for observability;
	// the node-agent's actual dispatch key is source_kata_socket.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// snapshot_id is the opaque identifier the storage backend uses to
	// namespace the persisted state files (e.g. the Snapshot CR's
	// namespace/name, or a UUID). Guaranteed unique per snapshot.
	SnapshotId string `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	// storage_backend names the StorageBackend implementation to route
	// to. Phase 3 ships only "local-disk".
	StorageBackend string `protobuf:"bytes,3,opt,name=storage_backend,json=storageBackend,proto3" json:"storage_backend,omitempty"`
	// source_kata_socket is the absolute path to the Firecracker API
	// socket Kata has exposed for the source microVM, usually under
	// /run/kata-containers/<sandbox-id>/firecracker.socket. The
	// operator resolves the placeholder and passes the concrete path.
	SourceKataSocket string `protobuf:"bytes,4,opt,name=source_kata_socket,json=sourceKataSocket,proto3" json:"source_kata_socket,omitempty"`
	// session_kek is the per-session key-encryption key session
	// checkpoints seal their DEKs with (setec#194, ADR-0007). The
	// operator reads it from the session's Kubernetes Secret and
	// forwards it over this mutually-authenticated mTLS channel; the
	// node-agent holds it in memory for the duration of the RPC only.
	// Cluster-scoped (unlike the node-local keyfile) so WHICHEVER node
	// resumes the session can unseal the checkpoint, and deleting the
	// Secret at session end crypto-erases every checkpoint it sealed.
	// Only valid with storage_backend "s3"; empty for every other
	// backend.
	SessionKek    []byte `protobuf:"bytes,5,opt,name=session_kek,json=sessionKek,proto3" json:"session_kek,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSnapshotRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *CreateSnapshotRequest) GetStorageBackend() string {
	if x != nil {
		return x.StorageBackend
	}
	return ""
}

func (x *CreateSnapshotRequest) GetSourceKataSocket() string {
	if x != nil {
		return x.SourceKataSocket
	}
	return ""
}

func (x *CreateSnapshotRequest) GetSessionKek() []byte {
	if x != nil {
		return x.SessionKek
	}
	return nil
}

// CreateSnapshotResponse carries the backend ref for the persisted
// state plus integrity metadata the operator writes into the Snapshot
// CR.
type CreateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageRef    string                 `protobuf:"bytes,1,opt,name=storage_ref,json=storageRef,proto3" json:"storage_ref,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSnapshotResponse) GetStorageRef() string {
	if x != nil {
		return x.StorageRef
	}
	return ""
}

func (x *CreateSnapshotResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateSnapshotResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// RestoreSandboxRequest identifies a snapshot to load into a fresh
// Firecracker VM attached to the caller-provided Kata socket.
type RestoreSandboxRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId     string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	StorageRef     string                 `protobuf:"bytes,2,opt,name=storage_ref,json=storageRef,proto3" json:"storage_ref,omitempty"`
	StorageBackend string                 `protobuf:"bytes,3,opt,name=storage_backend,json=storageBackend,proto3" json:"storage_backend,omitempty"`
	// kata_socket_target is the Firecracker API socket the target Pod's
	// Kata sandbox has exposed. The node-agent speaks to this socket to
	// instantiate the restored VM.
	KataSocketTarget string `protobuf:"bytes,4,opt,name=kata_socket_target,json=kataSocketTarget,proto3" json:"kata_socket_target,omitempty"`
	// resources optionally overrides the VM resource shape during
	// restore. When zero-valued the shape baked into the snapshot is
	// used as-is.
	Resources *Resources `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	// sandbox_id is the composite <namespace>/<name> of the Sandbox the
	// restore targets. Used as the ownership key for the node-local
	// vsock-CID uniqueness registry (ADR-0005 invariant 2): two
	// Sandboxes restored from the same snapshot state would otherwise
	// share the snapshotted guest CID undetected.
	SandboxId string `protobuf:"bytes,6,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// pod_ip is the CNI-assigned IP of the Sandbox's Pod. The restored
	// guest carries the snapshot-time network state in memory; the
	// node-agent directs the in-guest agent to reconcile its primary
	// interface to this address and fails the restore closed when the
	// guest cannot confirm it (ADR-0005 invariant 2).
	PodIp string `protobuf:"bytes,7,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	// hostname is the fresh hostname the restored guest must adopt
	// (derived from the Sandbox name). Part of the per-restore
	// uniquification set together with machine-id and boot-id.
	Hostname string `protobuf:"bytes,8,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// session_kek mirrors CreateSnapshotRequest.session_kek: the
	// per-session key-encryption key needed to unseal a session
	// checkpoint's DEK. Required (and only valid) when storage_backend
	// is "s3". This is what lets a checkpoint written by a drained or
	// dead node restore on a different node (setec#194).
	SessionKek    []byte `protobuf:"bytes,9,opt,name=session_kek,json=sessionKek,proto3" json:"session_kek,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSandboxRequest) Reset() {
	*x = RestoreSandboxRequest{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSandboxRequest) ProtoMessage() {}

func (x *RestoreSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSandboxRequest.ProtoReflect.Descriptor instead.
func (*RestoreSandboxRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{2}
}

func (x *RestoreSandboxRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *RestoreSandboxRequest) GetStorageRef() string {
	if x != nil {
		return x.StorageRef
	}
	return ""
}

func (x *RestoreSandboxRequest) GetStorageBackend() string {
	if x != nil {
		return x.StorageBackend
	}
	return ""
}

func (x *RestoreSandboxRequest) GetKataSocketTarget() string {
	if x != nil {
		return x.KataSocketTarget
	}
	return ""
}

func (x *RestoreSandboxRequest) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *RestoreSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RestoreSandboxRequest) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *RestoreSandboxRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RestoreSandboxRequest) GetSessionKek() []byte {
	if x != nil {
		return x.SessionKek
	}
	return nil
}

// RestoreSandboxResponse reports success/failure of the restore.
type RestoreSandboxResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// entropy_reseeded reports whether the restored guest's CSPRNG was
	// actively reseeded over vsock and the guest acknowledged the fresh
	// entropy (setec#72). When the node-agent runs with entropy reseed
	// enforcement (the default), success=true implies
	// entropy_reseeded=true; false alongside success=true can only
	// happen when the operator explicitly opted out
	// (--entropy-reseed=off), leaving only the passive virtio-rng
	// mechanism.
	EntropyReseeded bool `protobuf:"varint,3,opt,name=entropy_reseeded,json=entropyReseeded,proto3" json:"entropy_reseeded,omitempty"`
	// uniquified reports whether the restored guest verifiably applied
	// its per-restore identity (fresh machine-id, boot-id, hostname,
	// CNI-assigned Pod IP) and its vsock CID was confirmed unique on
	// the node (ADR-0005 invariant 2, setec#189). When the node-agent
	// runs with restore uniquification enforcement (the default),
	// success=true implies uniquified=true; false alongside
	// success=true can only happen when the operator explicitly opted
	// out (--restore-uniquify=off).
	Uniquified    bool `protobuf:"varint,4,opt,name=uniquified,proto3" json:"uniquified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSandboxResponse) Reset() {
	*x = RestoreSandboxResponse{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSandboxResponse) ProtoMessage() {}

func (x *RestoreSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSandboxResponse.ProtoReflect.Descriptor instead.
func (*RestoreSandboxResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{3}
}

func (x *RestoreSandboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreSandboxResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RestoreSandboxResponse) GetEntropyReseeded() bool {
	if x != nil {
		return x.EntropyReseeded
	}
	return false
}

func (x *RestoreSandboxResponse) GetUniquified() bool {
	if x != nil {
		return x.Uniquified
	}
	return false
}

// PauseSandboxRequest / PauseSandboxResponse wrap a direct
// Firecracker PATCH /vm state=Paused.
type PauseSandboxRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SandboxId        string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	KataSocketTarget string                 `protobuf:"bytes,2,opt,name=kata_socket_target,json=kataSocketTarget,proto3" json:"kata_socket_target,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PauseSandboxRequest) Reset() {
	*x = PauseSandboxRequest{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSandboxRequest) ProtoMessage() {}

func (x *PauseSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSandboxRequest.ProtoReflect.Descriptor instead.
func (*PauseSandboxRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{4}
}

func (x *PauseSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *PauseSandboxRequest) GetKataSocketTarget() string {
	if x != nil {
		return x.KataSocketTarget
	}
	return ""
}

type PauseSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSandboxResponse) Reset() {
	*x = PauseSandboxResponse{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSandboxResponse) ProtoMessage() {}

func (x *PauseSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSandboxResponse.ProtoReflect.Descriptor instead.
func (*PauseSandboxResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{5}
}

func (x *PauseSandboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PauseSandboxResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ResumeSandboxRequest / ResumeSandboxResponse wrap the resume
// counterpart.
type ResumeSandboxRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SandboxId        string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	KataSocketTarget string                 `protobuf:"bytes,2,opt,name=kata_socket_target,json=kataSocketTarget,proto3" json:"kata_socket_target,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResumeSandboxRequest) Reset() {
	*x = ResumeSandboxRequest{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSandboxRequest) ProtoMessage() {}

func (x *ResumeSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSandboxRequest.ProtoReflect.Descriptor instead.
func (*ResumeSandboxRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{6}
}

func (x *ResumeSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ResumeSandboxRequest) GetKataSocketTarget() string {
	if x != nil {
		return x.KataSocketTarget
	}
	return ""
}

type ResumeSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSandboxResponse) Reset() {
	*x = ResumeSandboxResponse{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSandboxResponse) ProtoMessage() {}

func (x *ResumeSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSandboxResponse.ProtoReflect.Descriptor instead.
func (*ResumeSandboxResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{7}
}

func (x *ResumeSandboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResumeSandboxResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// QueryPoolRequest asks the node-agent to report pre-warm pool entries
// compatible with the given class (optionally filtered by image).
type QueryPoolRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SandboxClass string                 `protobuf:"bytes,1,opt,name=sandbox_class,json=sandboxClass,proto3" json:"sandbox_class,omitempty"`
	// image_ref, when set, restricts the response to entries whose
	// underlying image matches. Empty means any image for the class.
	ImageRef      string `protobuf:"bytes,2,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPoolRequest) Reset() {
	*x = QueryPoolRequest{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPoolRequest) ProtoMessage() {}

func (x *QueryPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPoolRequest.ProtoReflect.Descriptor instead.
func (*QueryPoolRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{8}
}

func (x *QueryPoolRequest) GetSandboxClass() string {
	if x != nil {
		return x.SandboxClass
	}
	return ""
}

func (x *QueryPoolRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

// QueryPoolResponse enumerates the pool entries currently available on
// the node. The operator treats the list as a snapshot — an entry
// reported here may still race to Claim with another operator.
type QueryPoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*PoolEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPoolResponse) Reset() {
	*x = QueryPoolResponse{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPoolResponse) ProtoMessage() {}

func (x *QueryPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPoolResponse.ProtoReflect.Descriptor instead.
func (*QueryPoolResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{9}
}

func (x *QueryPoolResponse) GetEntries() []*PoolEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// PoolEntry is a single paused microVM the node has ready for an
// on-demand restore.
type PoolEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	ImageRef      string                 `protobuf:"bytes,2,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	Available     bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	AgeSeconds    int64                  `protobuf:"varint,4,opt,name=age_seconds,json=ageSeconds,proto3" json:"age_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolEntry) Reset() {
	*x = PoolEntry{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolEntry) ProtoMessage() {}

func (x *PoolEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolEntry.ProtoReflect.Descriptor instead.
func (*PoolEntry) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{10}
}

func (x *PoolEntry) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *PoolEntry) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *PoolEntry) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *PoolEntry) GetAgeSeconds() int64 {
	if x != nil {
		return x.AgeSeconds
	}
	return 0
}

// ClaimPoolEntryRequest identifies the class (and optionally image)
// an ephemeral Sandbox wants a warm start for, plus the Firecracker
// socket of the Sandbox's freshly-created kata-fc Pod that the pool
// state should be restored into.
type ClaimPoolEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sandbox_class is the SandboxClass the pool entry must belong to.
	SandboxClass string `protobuf:"bytes,1,opt,name=sandbox_class,json=sandboxClass,proto3" json:"sandbox_class,omitempty"`
	// image_ref, when set, requires the claimed entry's baked image to
	// match. Empty accepts any entry for the class.
	ImageRef string `protobuf:"bytes,2,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	// kata_socket_target is the Firecracker API socket the target Pod's
	// Kata sandbox has exposed; the restored VM state lands here.
	KataSocketTarget string `protobuf:"bytes,3,opt,name=kata_socket_target,json=kataSocketTarget,proto3" json:"kata_socket_target,omitempty"`
	// sandbox_id is the composite <namespace>/<name> of the requesting
	// Sandbox. Also the ownership key for the node-local vsock-CID
	// uniqueness registry (ADR-0005 invariant 2).
	SandboxId string `protobuf:"bytes,4,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// pod_ip is the CNI-assigned IP of the Sandbox's Pod; the restored
	// guest must observe it (see RestoreSandboxRequest.pod_ip).
	PodIp string `protobuf:"bytes,5,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	// hostname is the fresh hostname the restored guest must adopt
	// (see RestoreSandboxRequest.hostname).
	Hostname      string `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimPoolEntryRequest) Reset() {
	*x = ClaimPoolEntryRequest{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimPoolEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimPoolEntryRequest) ProtoMessage() {}

func (x *ClaimPoolEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimPoolEntryRequest.ProtoReflect.Descriptor instead.
func (*ClaimPoolEntryRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{11}
}

func (x *ClaimPoolEntryRequest) GetSandboxClass() string {
	if x != nil {
		return x.SandboxClass
	}
	return ""
}

func (x *ClaimPoolEntryRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *ClaimPoolEntryRequest) GetKataSocketTarget() string {
	if x != nil {
		return x.KataSocketTarget
	}
	return ""
}

func (x *ClaimPoolEntryRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ClaimPoolEntryRequest) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *ClaimPoolEntryRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

// ClaimPoolEntryResponse reports the claim + restore outcome.
type ClaimPoolEntryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// claimed is false when no compatible entry existed. The caller
	// falls back to cold boot; this is not an error.
	Claimed bool `protobuf:"varint,1,opt,name=claimed,proto3" json:"claimed,omitempty"`
	// success reports the restore outcome for a claimed entry. A
	// claimed entry that failed to restore is torn down node-side; the
	// caller falls back to cold boot.
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// entry_id identifies the consumed entry (empty when claimed=false).
	EntryId string `protobuf:"bytes,3,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Error   string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// entropy_reseeded mirrors RestoreSandboxResponse.entropy_reseeded:
	// the restored guest's CSPRNG verifiably received fresh entropy
	// (setec#72) before the warm start was reported successful.
	EntropyReseeded bool `protobuf:"varint,5,opt,name=entropy_reseeded,json=entropyReseeded,proto3" json:"entropy_reseeded,omitempty"`
	// uniquified mirrors RestoreSandboxResponse.uniquified: the
	// restored guest verifiably applied its per-restore identity and
	// its vsock CID was confirmed unique on the node (ADR-0005
	// invariant 2, setec#189).
	Uniquified    bool `protobuf:"varint,6,opt,name=uniquified,proto3" json:"uniquified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimPoolEntryResponse) Reset() {
	*x = ClaimPoolEntryResponse{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimPoolEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimPoolEntryResponse) ProtoMessage() {}

func (x *ClaimPoolEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimPoolEntryResponse.ProtoReflect.Descriptor instead.
func (*ClaimPoolEntryResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{12}
}

func (x *ClaimPoolEntryResponse) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

func (x *ClaimPoolEntryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClaimPoolEntryResponse) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *ClaimPoolEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ClaimPoolEntryResponse) GetEntropyReseeded() bool {
	if x != nil {
		return x.EntropyReseeded
	}
	return false
}

func (x *ClaimPoolEntryResponse) GetUniquified() bool {
	if x != nil {
		return x.Uniquified
	}
	return false
}

// DeleteSnapshotRequest / DeleteSnapshotResponse wrap a
// Storage.Delete call on the node.
type DeleteSnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId     string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	StorageRef     string                 `protobuf:"bytes,2,opt,name=storage_ref,json=storageRef,proto3" json:"storage_ref,omitempty"`
	StorageBackend string                 `protobuf:"bytes,3,opt,name=storage_backend,json=storageBackend,proto3" json:"storage_backend,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *DeleteSnapshotRequest) GetStorageRef() string {
	if x != nil {
		return x.StorageRef
	}
	return ""
}

func (x *DeleteSnapshotRequest) GetStorageBackend() string {
	if x != nil {
		return x.StorageBackend
	}
	return ""
}

type DeleteSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_nodeagent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_nodeagent_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSnapshotResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_grpc_v1_nodeagent_proto protoreflect.FileDescriptor

var file_api_grpc_v1_nodeagent_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x6f,
	0x64, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73,
	0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xcf, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x42, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x6b, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4b, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b,
	0x65, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4b, 0x65, 0x6b, 0x22, 0x70, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x22, 0xd6, 0x02, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x66,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x66, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x6b,
	0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6b, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x31, 0x0a, 0x09, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73,
	0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x70,
	0x6f, 0x64, 0x5f, 0x69, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x64,
	0x49, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x6b, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x6b, 0x22,
	0x93, 0x01, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x29, 0x0a, 0x10, 0x65, 0x6e,
	0x74, 0x72, 0x6f, 0x70, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x65, 0x64, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x65, 0x6e, 0x74, 0x72, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x73,
	0x65, 0x65, 0x64, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x62, 0x0a, 0x13, 0x50, 0x61, 0x75, 0x73, 0x65, 0x53, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x6b,
	0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6b, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x46, 0x0a, 0x14, 0x50, 0x61, 0x75,
	0x73, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x63, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x6b, 0x61, 0x74, 0x61,
	0x5f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6b, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x47, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x54, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x66, 0x22, 0x42, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6f,
	0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65,
	0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x82, 0x01, 0x0a, 0x09, 0x50, 0x6f,
	0x6f, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x12,
	0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x61, 0x67, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0xd9,
	0x01, 0x0a, 0x15, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x50, 0x6f, 0x6f, 0x6c, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x12, 0x2c, 0x0a, 0x12, 0x6b, 0x61,
	0x74, 0x61, 0x5f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6b, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x6f, 0x64, 0x5f, 0x69,
	0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x64, 0x49, 0x70, 0x12, 0x1a,
	0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xc8, 0x01, 0x0a, 0x16, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x50, 0x6f, 0x6f, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x29, 0x0a, 0x10, 0x65, 0x6e,
	0x74, 0x72, 0x6f, 0x70, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x65, 0x64, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x65, 0x6e, 0x74, 0x72, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x73,
	0x65, 0x65, 0x64, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x82, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x66, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x22, 0x48, 0x0a, 0x16, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x32, 0xcd, 0x04, 0x0a, 0x10, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x0e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x1f, 0x2e, 0x73, 0x65,
	0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73,
	0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53,
	0x0a, 0x0e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x12, 0x1f, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0c, 0x50, 0x61, 0x75, 0x73, 0x65, 0x53, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x12, 0x1d, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x61, 0x75, 0x73, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61,
	0x75, 0x73, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x53, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x12, 0x1e, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6f, 0x6f,
	0x6c, 0x12, 0x1a, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6f,
	0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0e, 0x43, 0x6c,
	0x61, 0x69, 0x6d, 0x50, 0x6f, 0x6f, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1f, 0x2e, 0x73,
	0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x50, 0x6f, 0x6f,
	0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x50, 0x6f,
	0x6f, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x53, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x12, 0x1f, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x7a, 0x65, 0x72, 0x6f, 0x72, 0x6f, 0x6f, 0x74, 0x2d, 0x61, 0x69, 0x2f, 0x73,
	0x65, 0x74, 0x65, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31,
	0x3b, 0x73, 0x65, 0x74, 0x65, 0x63, 0x76, 0x31, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_api_grpc_v1_nodeagent_proto_rawDescOnce sync.Once
	file_api_grpc_v1_nodeagent_proto_rawDescData []byte
)

func file_api_grpc_v1_nodeagent_proto_rawDescGZIP() []byte {
	file_api_grpc_v1_nodeagent_proto_rawDescOnce.Do(func() {
		file_api_grpc_v1_nodeagent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_v1_nodeagent_proto_rawDesc), len(file_api_grpc_v1_nodeagent_proto_rawDesc)))
	})
	return file_api_grpc_v1_nodeagent_proto_rawDescData
}

var file_api_grpc_v1_nodeagent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_grpc_v1_nodeagent_proto_goTypes = []any{
	(*CreateSnapshotRequest)(nil),  // 0: setec.v1.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil), // 1: setec.v1.CreateSnapshotResponse
	(*RestoreSandboxRequest)(nil),  // 2: setec.v1.RestoreSandboxRequest
	(*RestoreSandboxResponse)(nil), // 3: setec.v1.RestoreSandboxResponse
	(*PauseSandboxRequest)(nil),    // 4: setec.v1.PauseSandboxRequest
	(*PauseSandboxResponse)(nil),   // 5: setec.v1.PauseSandboxResponse
	(*ResumeSandboxRequest)(nil),   // 6: setec.v1.ResumeSandboxRequest
	(*ResumeSandboxResponse)(nil),  // 7: setec.v1.ResumeSandboxResponse
	(*QueryPoolRequest)(nil),       // 8: setec.v1.QueryPoolRequest
	(*QueryPoolResponse)(nil),      // 9: setec.v1.QueryPoolResponse
	(*PoolEntry)(nil),              // 10: setec.v1.PoolEntry
	(*ClaimPoolEntryRequest)(nil),  // 11: setec.v1.ClaimPoolEntryRequest
	(*ClaimPoolEntryResponse)(nil), // 12: setec.v1.ClaimPoolEntryResponse
	(*DeleteSnapshotRequest)(nil),  // 13: setec.v1.DeleteSnapshotRequest
	(*DeleteSnapshotResponse)(nil), // 14: setec.v1.DeleteSnapshotResponse
	(*Resources)(nil),              // 15: setec.v1.Resources
}
var file_api_grpc_v1_nodeagent_proto_depIdxs = []int32{
	15, // 0: setec.v1.RestoreSandboxRequest.resources:type_name -> setec.v1.Resources
	10, // 1: setec.v1.QueryPoolResponse.entries:type_name -> setec.v1.PoolEntry
	0,  // 2: setec.v1.NodeAgentService.CreateSnapshot:input_type -> setec.v1.CreateSnapshotRequest
	2,  // 3: setec.v1.NodeAgentService.RestoreSandbox:input_type -> setec.v1.RestoreSandboxRequest
	4,  // 4: setec.v1.NodeAgentService.PauseSandbox:input_type -> setec.v1.PauseSandboxRequest
	6,  // 5: setec.v1.NodeAgentService.ResumeSandbox:input_type -> setec.v1.ResumeSandboxRequest
	8,  // 6: setec.v1.NodeAgentService.QueryPool:input_type -> setec.v1.QueryPoolRequest
	11, // 7: setec.v1.NodeAgentService.ClaimPoolEntry:input_type -> setec.v1.ClaimPoolEntryRequest
	13, // 8: setec.v1.NodeAgentService.DeleteSnapshot:input_type -> setec.v1.DeleteSnapshotRequest
	1,  // 9: setec.v1.NodeAgentService.CreateSnapshot:output_type -> setec.v1.CreateSnapshotResponse
	3,  // 10: setec.v1.NodeAgentService.RestoreSandbox:output_type -> setec.v1.RestoreSandboxResponse
	5,  // 11: setec.v1.NodeAgentService.PauseSandbox:output_type -> setec.v1.PauseSandboxResponse
	7,  // 12: setec.v1.NodeAgentService.ResumeSandbox:output_type -> setec.v1.ResumeSandboxResponse
	9,  // 13: setec.v1.NodeAgentService.QueryPool:output_type -> setec.v1.QueryPoolResponse
	12, // 14: setec.v1.NodeAgentService.ClaimPoolEntry:output_type -> setec.v1.ClaimPoolEntryResponse
	14, // 15: setec.v1.NodeAgentService.DeleteSnapshot:output_type -> setec.v1.DeleteSnapshotResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_grpc_v1_nodeagent_proto_init() }
func file_api_grpc_v1_nodeagent_proto_init() {
	if File_api_grpc_v1_nodeagent_proto != nil {
		return
	}
	file_api_grpc_v1_sandbox_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_v1_nodeagent_proto_rawDesc), len(file_api_grpc_v1_nodeagent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_v1_nodeagent_proto_goTypes,
		DependencyIndexes: file_api_grpc_v1_nodeagent_proto_depIdxs,
		MessageInfos:      file_api_grpc_v1_nodeagent_proto_msgTypes,
	}.Build()
	File_api_grpc_v1_nodeagent_proto = out.File
	file_api_grpc_v1_nodeagent_proto_goTypes = nil
	file_api_grpc_v1_nodeagent_proto_depIdxs = nil
}
