// Copyright 2026 The Setec Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: api/grpc/v1/sandbox.proto

package setecv1grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status discriminates "the command ran and this is its code" from
// every way an exec can end WITHOUT one. It exists because an exit
// code cannot be synthesised: a caller handed a bare stream close,
// or a zero-valued int32, cannot tell a clean success from a
// microVM that disappeared mid-build.
type SessionExecExit_Status int32

const (
	// STATUS_UNSPECIFIED is never sent. Its presence means the
	// message was not produced by a Setec frontend (or was
	// zero-valued in transit) and the outcome is unknown.
	SessionExecExit_STATUS_UNSPECIFIED SessionExecExit_Status = 0
	// STATUS_EXITED: the command ran to completion and the runtime
	// reported its wait status. exit_code is authoritative — and is
	// the ONLY status for which exit_code carries meaning.
	SessionExecExit_STATUS_EXITED SessionExecExit_Status = 1
	// STATUS_SANDBOX_GONE: the session's microVM stopped existing
	// while the command was running (evicted, node lost, session
	// torn down, Pod deleted). The command's outcome is unknown and
	// unknowable; it may have completed, failed, or been killed
	// part-way.
	SessionExecExit_STATUS_SANDBOX_GONE SessionExecExit_Status = 2
	// STATUS_TRANSPORT_FAILED: the exec channel to the microVM broke
	// before a wait status was read. As with SANDBOX_GONE the
	// command's outcome is unknown; unlike it, the session may still
	// be perfectly healthy and a retry may well succeed.
	SessionExecExit_STATUS_TRANSPORT_FAILED SessionExecExit_Status = 3
	// STATUS_CANCELED: the caller canceled the RPC (or its deadline
	// elapsed) and the command was terminated with it. Emitted
	// best-effort — a caller that has already gone away will not
	// receive it.
	SessionExecExit_STATUS_CANCELED SessionExecExit_Status = 4
)

// Enum value maps for SessionExecExit_Status.
var (
	SessionExecExit_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_EXITED",
		2: "STATUS_SANDBOX_GONE",
		3: "STATUS_TRANSPORT_FAILED",
		4: "STATUS_CANCELED",
	}
	SessionExecExit_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":      0,
		"STATUS_EXITED":           1,
		"STATUS_SANDBOX_GONE":     2,
		"STATUS_TRANSPORT_FAILED": 3,
		"STATUS_CANCELED":         4,
	}
)

func (x SessionExecExit_Status) Enum() *SessionExecExit_Status {
	p := new(SessionExecExit_Status)
	*p = x
	return p
}

func (x SessionExecExit_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionExecExit_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v1_sandbox_proto_enumTypes[0].Descriptor()
}

func (SessionExecExit_Status) Type() protoreflect.EnumType {
	return &file_api_grpc_v1_sandbox_proto_enumTypes[0]
}

func (x SessionExecExit_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionExecExit_Status.Descriptor instead.
func (SessionExecExit_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{19, 0}
}

// Reason is the typed failure class.
type AttachFailure_Reason int32

const (
	AttachFailure_REASON_UNSPECIFIED AttachFailure_Reason = 0
	// REASON_SESSION_NOT_FOUND: the handle resolves to no live
	// Sandbox in the caller's namespace (unknown name, deleted
	// Sandbox, or a UID that belongs to an earlier same-name Sandbox).
	AttachFailure_REASON_SESSION_NOT_FOUND AttachFailure_Reason = 1
	// REASON_SESSION_ENDED: the Sandbox exists but its session is
	// over — it reached a terminal phase or teardown is in progress.
	AttachFailure_REASON_SESSION_ENDED AttachFailure_Reason = 2
	// REASON_NOT_A_SESSION: the Sandbox follows the ephemeral
	// REASON_NOT_A_SESSION: the Sandbox follows the ephemeral
	// lifecycle, which rejects reattach (ADR-0006).
	AttachFailure_REASON_NOT_A_SESSION AttachFailure_Reason = 3
	// REASON_SESSION_NOT_RUNNING: Exec-only. The session is live but
	// its microVM could not be brought to Running in time — it is
	// still coming up, or a resume from paused/suspended did not
	// complete within the deadline. No command ran; the caller may
	// retry.
	AttachFailure_REASON_SESSION_NOT_RUNNING AttachFailure_Reason = 4
)

// Enum value maps for AttachFailure_Reason.
var (
	AttachFailure_Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "REASON_SESSION_NOT_FOUND",
		2: "REASON_SESSION_ENDED",
		3: "REASON_NOT_A_SESSION",
		4: "REASON_SESSION_NOT_RUNNING",
	}
	AttachFailure_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED":         0,
		"REASON_SESSION_NOT_FOUND":   1,
		"REASON_SESSION_ENDED":       2,
		"REASON_NOT_A_SESSION":       3,
		"REASON_SESSION_NOT_RUNNING": 4,
	}
)

func (x AttachFailure_Reason) Enum() *AttachFailure_Reason {
	p := new(AttachFailure_Reason)
	*p = x
	return p
}

func (x AttachFailure_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttachFailure_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v1_sandbox_proto_enumTypes[1].Descriptor()
}

func (AttachFailure_Reason) Type() protoreflect.EnumType {
	return &file_api_grpc_v1_sandbox_proto_enumTypes[1]
}

func (x AttachFailure_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttachFailure_Reason.Descriptor instead.
func (AttachFailure_Reason) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{20, 0}
}

// LaunchRequest carries everything needed to construct the Sandbox spec.
type LaunchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of a cluster-scoped SandboxClass (optional; empty defers to
	// the cluster-default).
	SandboxClass string `protobuf:"bytes,1,opt,name=sandbox_class,json=sandboxClass,proto3" json:"sandbox_class,omitempty"`
	// OCI reference the microVM will run. Required.
	Image string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// Command executed inside the microVM. At least one entry required.
	Command []string `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	// Environment variables exposed to the workload. Optional.
	Env map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Resource budget. Required for classes without DefaultResources.
	Resources *Resources `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	// Network policy intent. Optional; defaults to mode=full.
	Network *Network `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	// Lifecycle constraints (timeout). Optional.
	Lifecycle     *Lifecycle `protobuf:"bytes,7,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRequest) Reset() {
	*x = LaunchRequest{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRequest) ProtoMessage() {}

func (x *LaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRequest.ProtoReflect.Descriptor instead.
func (*LaunchRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *LaunchRequest) GetSandboxClass() string {
	if x != nil {
		return x.SandboxClass
	}
	return ""
}

func (x *LaunchRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *LaunchRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *LaunchRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *LaunchRequest) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *LaunchRequest) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *LaunchRequest) GetLifecycle() *Lifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return nil
}

// LaunchResponse identifies the Sandbox created for the caller.
type LaunchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sandbox_id is the composite <namespace>/<name>/<uid> tuple used by
	// subsequent RPCs.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// sandbox_class is the SandboxClass the created Sandbox was bound
	// to, read back from the created object after admission (so any
	// admission-time defaulting is reflected, not the request value).
	// Empty means the class is not yet resolved: the request named no
	// class and the cluster-default resolution happens when the operator
	// schedules the Sandbox. The authoritative post-resolution values
	// are reported on WaitResponse and AttachResponse.
	SandboxClass  string `protobuf:"bytes,4,opt,name=sandbox_class,json=sandboxClass,proto3" json:"sandbox_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchResponse) Reset() {
	*x = LaunchResponse{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchResponse) ProtoMessage() {}

func (x *LaunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchResponse.ProtoReflect.Descriptor instead.
func (*LaunchResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *LaunchResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *LaunchResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LaunchResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LaunchResponse) GetSandboxClass() string {
	if x != nil {
		return x.SandboxClass
	}
	return ""
}

// Resources mirrors Sandbox.spec.resources.
type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vcpu          uint32                 `protobuf:"varint,1,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	Memory        string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"` // resource.Quantity string ("2Gi", "512Mi", ...)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *Resources) GetVcpu() uint32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *Resources) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

// Network mirrors Sandbox.spec.network.
type Network struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"` // one of: full, egress-allow-list, none
	Allow         []*NetworkAllow        `protobuf:"bytes,2,rep,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *Network) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Network) GetAllow() []*NetworkAllow {
	if x != nil {
		return x.Allow
	}
	return nil
}

// NetworkAllow mirrors Sandbox.spec.network.allow entries.
type NetworkAllow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAllow) Reset() {
	*x = NetworkAllow{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAllow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAllow) ProtoMessage() {}

func (x *NetworkAllow) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAllow.ProtoReflect.Descriptor instead.
func (*NetworkAllow) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkAllow) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NetworkAllow) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Lifecycle mirrors Sandbox.spec.lifecycle.
type Lifecycle struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Timeout string                 `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"` // Go-style duration: "30m", "8h"
	// mode selects the Sandbox lifecycle (ADR-0006): "ephemeral"
	// (default when empty; run-to-completion, auto-destroy, stateless)
	// or "session" (long-lived, durable /workspace volume, explicit
	// teardown via Kill). Mode is immutable for the life of a Sandbox.
	Mode string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	// workspace configures the durable per-session workspace volume.
	// Only meaningful when mode is "session"; rejected otherwise.
	Workspace     *Workspace `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lifecycle) Reset() {
	*x = Lifecycle{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lifecycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lifecycle) ProtoMessage() {}

func (x *Lifecycle) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lifecycle.ProtoReflect.Descriptor instead.
func (*Lifecycle) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *Lifecycle) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *Lifecycle) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Lifecycle) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

// Workspace mirrors Sandbox.spec.lifecycle.workspace: the durable
// per-session ReadWriteOnce CSI volume mounted at /workspace. Data
// written there survives VM restart and node loss, and is wiped and
// deleted at session teardown.
type Workspace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// size is the requested PVC capacity as a resource.Quantity string
	// ("10Gi", "512Mi"). Empty means the operator default (10Gi).
	Size string `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	// storage_class_name selects the StorageClass the workspace is
	// provisioned from; empty means the cluster default. Encryption at
	// rest is the StorageClass's responsibility — point this at a class
	// whose CSI driver encrypts volumes.
	StorageClassName string `protobuf:"bytes,2,opt,name=storage_class_name,json=storageClassName,proto3" json:"storage_class_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *Workspace) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Workspace) GetStorageClassName() string {
	if x != nil {
		return x.StorageClassName
	}
	return ""
}

// StreamLogsRequest selects the Sandbox and optionally follows new
// output until the Pod terminates.
type StreamLogsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SandboxId string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Follow    bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	// tail_lines, when positive, starts the stream that many lines from
	// the end of the log instead of at the beginning. A client that
	// reconnects to a long-lived Sandbox sets it, so it receives a
	// bounded tail plus every new line, instead of replaying weeks of
	// output. Zero sends the whole log the kubelet still holds.
	// Negative is INVALID_ARGUMENT.
	TailLines     int64 `protobuf:"varint,3,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *StreamLogsRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *StreamLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *StreamLogsRequest) GetTailLines() int64 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

// StreamLogsResponse is a single-stream log payload. `stream` is "stdout" or
// "stderr".
type StreamLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsResponse) Reset() {
	*x = StreamLogsResponse{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsResponse) ProtoMessage() {}

func (x *StreamLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsResponse.ProtoReflect.Descriptor instead.
func (*StreamLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *StreamLogsResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamLogsResponse) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

// WaitRequest blocks until the given Sandbox reaches a terminal phase.
type WaitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitRequest) Reset() {
	*x = WaitRequest{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitRequest) ProtoMessage() {}

func (x *WaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitRequest.ProtoReflect.Descriptor instead.
func (*WaitRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{9}
}

func (x *WaitRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

// WaitResponse carries the Sandbox's terminal outcome.
type WaitResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Phase    string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	ExitCode int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Reason   string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// runtime is the backend actually selected for the Sandbox after
	// evaluating its SandboxClass's primary backend and any fallback
	// chain (status.runtime.chosen): one of kata-fc, kata-qemu, gvisor,
	// runc. Wait returns after the Sandbox is terminal, so this value is
	// authoritative. Empty means no backend was ever resolved — the
	// Sandbox reached a terminal phase before selection (for example
	// ClassNotFound or RuntimeUnavailable) — never "resolved but
	// unreported".
	Runtime       string `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitResponse) Reset() {
	*x = WaitResponse{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitResponse) ProtoMessage() {}

func (x *WaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitResponse.ProtoReflect.Descriptor instead.
func (*WaitResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *WaitResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *WaitResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *WaitResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *WaitResponse) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

// KillRequest deletes a Sandbox.
type KillRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SandboxId string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// grace_seconds is how long the workload gets between SIGTERM and
	// SIGKILL, so a long-lived driver can checkpoint its work before the
	// microVM goes away. When positive the frontend deletes the Sandbox
	// Pod with this grace period first, then the Sandbox object; the
	// kubelet sends SIGTERM at once and SIGKILL after grace_seconds.
	// Zero keeps the Pod's own terminationGracePeriodSeconds (the
	// Kubernetes default of 30 s). Negative is INVALID_ARGUMENT.
	GraceSeconds  int64 `protobuf:"varint,2,opt,name=grace_seconds,json=graceSeconds,proto3" json:"grace_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{11}
}

func (x *KillRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *KillRequest) GetGraceSeconds() int64 {
	if x != nil {
		return x.GraceSeconds
	}
	return 0
}

// KillResponse is currently empty; a Sandbox that could not be deleted
// surfaces the failure via gRPC status.
type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{12}
}

// AttachRequest presents the session handle to reattach to. The handle
// is the sandbox_id returned by Launch (<namespace>/<name>/<uid>); the
// UID pins the handle to one session so a later same-name Sandbox can
// never be reached with an old handle.
type AttachRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{13}
}

func (x *AttachRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

// AttachResponse confirms the handle resolved to a live session and
// reports where the session currently stands. The returned sandbox_id
// equals the request handle and remains the key for every subsequent
// RPC (StreamLogs, Wait, Kill).
type AttachResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SandboxId string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// phase is the session Sandbox's current lifecycle phase (Pending,
	// Running, Paused, ...). A session whose VM is being replaced after
	// a crash reports Pending with the VM restart under way; the caller
	// may attach and stream as soon as the fresh VM is up.
	Phase string `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	// sandbox_class is the SandboxClass the Sandbox is bound to
	// (spec.sandboxClassName). Reported here so a reattaching caller —
	// which never saw the LaunchResponse — can confirm what it is
	// attached to. Empty means the Sandbox named no class and defers to
	// the cluster default.
	SandboxClass string `protobuf:"bytes,5,opt,name=sandbox_class,json=sandboxClass,proto3" json:"sandbox_class,omitempty"`
	// runtime is the backend selected for the Sandbox
	// (status.runtime.chosen): one of kata-fc, kata-qemu, gvisor, runc.
	// Empty means the operator has not yet resolved a backend (the
	// Sandbox is still Pending), not "resolved but unreported".
	Runtime       string `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachResponse) Reset() {
	*x = AttachResponse{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse) ProtoMessage() {}

func (x *AttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachResponse.ProtoReflect.Descriptor instead.
func (*AttachResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{14}
}

func (x *AttachResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *AttachResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttachResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AttachResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *AttachResponse) GetSandboxClass() string {
	if x != nil {
		return x.SandboxClass
	}
	return ""
}

func (x *AttachResponse) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

// SandboxServiceExecRequest is one message of the client half of an
// Exec stream. The verbose name is buf's collision-safe form: this
// package already has a LeaseService.Exec with its own ExecRequest,
// and the two verbs must never be mistaken for each other.
// The first message MUST carry `start`; every later message carries
// stdin bytes or the stdin half-close. A second `start`, or any other
// message before the first `start`, is INVALID_ARGUMENT.
type SandboxServiceExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*SandboxServiceExecRequest_Start
	//	*SandboxServiceExecRequest_Stdin
	//	*SandboxServiceExecRequest_StdinEof
	Request       isSandboxServiceExecRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxServiceExecRequest) Reset() {
	*x = SandboxServiceExecRequest{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxServiceExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxServiceExecRequest) ProtoMessage() {}

func (x *SandboxServiceExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxServiceExecRequest.ProtoReflect.Descriptor instead.
func (*SandboxServiceExecRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{15}
}

func (x *SandboxServiceExecRequest) GetRequest() isSandboxServiceExecRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *SandboxServiceExecRequest) GetStart() *SessionExecStart {
	if x != nil {
		if x, ok := x.Request.(*SandboxServiceExecRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *SandboxServiceExecRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Request.(*SandboxServiceExecRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *SandboxServiceExecRequest) GetStdinEof() bool {
	if x != nil {
		if x, ok := x.Request.(*SandboxServiceExecRequest_StdinEof); ok {
			return x.StdinEof
		}
	}
	return false
}

type isSandboxServiceExecRequest_Request interface {
	isSandboxServiceExecRequest_Request()
}

type SandboxServiceExecRequest_Start struct {
	// start opens the exec. Exactly once, first.
	Start *SessionExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type SandboxServiceExecRequest_Stdin struct {
	// stdin is a chunk of standard input for the running command.
	// Ignored (with the stream failed) before start.
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type SandboxServiceExecRequest_StdinEof struct {
	// stdin_eof closes the command's standard input. A command that
	// reads to EOF hangs forever without it. Set to true to
	// half-close; the value false is meaningless and ignored. Sending
	// stdin after stdin_eof is INVALID_ARGUMENT.
	StdinEof bool `protobuf:"varint,3,opt,name=stdin_eof,json=stdinEof,proto3,oneof"`
}

func (*SandboxServiceExecRequest_Start) isSandboxServiceExecRequest_Request() {}

func (*SandboxServiceExecRequest_Stdin) isSandboxServiceExecRequest_Request() {}

func (*SandboxServiceExecRequest_StdinEof) isSandboxServiceExecRequest_Request() {}

// SessionExecStart names the session and the command to run in it.
type SessionExecStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sandbox_id is the session handle (<namespace>/<name>/<uid>)
	// returned by Launch — the same handle Attach resolves. Required.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// command is the argv to execute, executed directly (no shell is
	// interposed, so no quoting, globbing, or redirection is applied by
	// Setec). At least one entry is required.
	//
	// The command inherits the session container's environment and
	// working directory (/workspace). Setec deliberately offers no
	// per-exec env or cwd override: the container runtime's exec
	// primitive takes neither, and synthesising them would mean
	// wrapping argv in a shell and silently changing its meaning.
	// Callers that want either should run their own shell explicitly.
	Command       []string `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionExecStart) Reset() {
	*x = SessionExecStart{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionExecStart) ProtoMessage() {}

func (x *SessionExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionExecStart.ProtoReflect.Descriptor instead.
func (*SessionExecStart) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{16}
}

func (x *SessionExecStart) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SessionExecStart) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

// SandboxServiceExecResponse is one message of the server half of an
// Exec stream: output while the command runs, then exactly one
// terminal exit.
type SandboxServiceExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*SandboxServiceExecResponse_Output
	//	*SandboxServiceExecResponse_Exit
	Response      isSandboxServiceExecResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxServiceExecResponse) Reset() {
	*x = SandboxServiceExecResponse{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxServiceExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxServiceExecResponse) ProtoMessage() {}

func (x *SandboxServiceExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxServiceExecResponse.ProtoReflect.Descriptor instead.
func (*SandboxServiceExecResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{17}
}

func (x *SandboxServiceExecResponse) GetResponse() isSandboxServiceExecResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SandboxServiceExecResponse) GetOutput() *SessionExecOutput {
	if x != nil {
		if x, ok := x.Response.(*SandboxServiceExecResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *SandboxServiceExecResponse) GetExit() *SessionExecExit {
	if x != nil {
		if x, ok := x.Response.(*SandboxServiceExecResponse_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isSandboxServiceExecResponse_Response interface {
	isSandboxServiceExecResponse_Response()
}

type SandboxServiceExecResponse_Output struct {
	Output *SessionExecOutput `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type SandboxServiceExecResponse_Exit struct {
	Exit *SessionExecExit `protobuf:"bytes,2,opt,name=exit,proto3,oneof"`
}

func (*SandboxServiceExecResponse_Output) isSandboxServiceExecResponse_Response() {}

func (*SandboxServiceExecResponse_Exit) isSandboxServiceExecResponse_Response() {}

// SessionExecOutput is a chunk of the command's output. `stream` is "stdout"
// or "stderr", matching StreamLogsResponse. stdout and stderr stay
// separated — Exec never merges them.
type SessionExecOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionExecOutput) Reset() {
	*x = SessionExecOutput{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionExecOutput) ProtoMessage() {}

func (x *SessionExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionExecOutput.ProtoReflect.Descriptor instead.
func (*SessionExecOutput) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{18}
}

func (x *SessionExecOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SessionExecOutput) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

// SessionExecExit terminates an Exec stream with a definitive verdict.
// Exactly one is sent per established Exec, and it is always the last
// message on the stream.
type SessionExecExit struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status SessionExecExit_Status `protobuf:"varint,1,opt,name=status,proto3,enum=setec.v1.SessionExecExit_Status" json:"status,omitempty"`
	// exit_code is the command's wait status. Meaningful ONLY when
	// status is STATUS_EXITED; always 0 otherwise, and 0 there means
	// "no code was ever reported", never "success".
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// message is a human-readable elaboration for non-EXITED statuses
	// (empty for STATUS_EXITED). Diagnostics only — never parse it.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionExecExit) Reset() {
	*x = SessionExecExit{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionExecExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionExecExit) ProtoMessage() {}

func (x *SessionExecExit) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionExecExit.ProtoReflect.Descriptor instead.
func (*SessionExecExit) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{19}
}

func (x *SessionExecExit) GetStatus() SessionExecExit_Status {
	if x != nil {
		return x.Status
	}
	return SessionExecExit_STATUS_UNSPECIFIED
}

func (x *SessionExecExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *SessionExecExit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AttachFailure is the typed session-handle resolution failure
// attached to the gRPC status details of a failed Attach or Exec, so
// callers act on the failure class programmatically rather than
// parsing message text. (The name predates Exec; the detail is shared
// deliberately so a caller keeps one switch for both verbs.)
type AttachFailure struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Reason AttachFailure_Reason   `protobuf:"varint,1,opt,name=reason,proto3,enum=setec.v1.AttachFailure_Reason" json:"reason,omitempty"`
	// phase carries the Sandbox's terminal phase when reason is
	// REASON_SESSION_ENDED ("Completed" or "Failed"); empty otherwise.
	Phase         string `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachFailure) Reset() {
	*x = AttachFailure{}
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachFailure) ProtoMessage() {}

func (x *AttachFailure) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sandbox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachFailure.ProtoReflect.Descriptor instead.
func (*AttachFailure) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sandbox_proto_rawDescGZIP(), []int{20}
}

func (x *AttachFailure) GetReason() AttachFailure_Reason {
	if x != nil {
		return x.Reason
	}
	return AttachFailure_REASON_UNSPECIFIED
}

func (x *AttachFailure) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

var File_api_grpc_v1_sandbox_proto protoreflect.FileDescriptor

var file_api_grpc_v1_sandbox_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x74,
	0x65, 0x63, 0x2e, 0x76, 0x31, 0x22, 0xe3, 0x02, 0x0a, 0x0d, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x32, 0x0a, 0x03,
	0x65, 0x6e, 0x76, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x65, 0x74, 0x65,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x65, 0x6e, 0x76,
	0x12, 0x31, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x12, 0x31, 0x0a, 0x09, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x52, 0x09, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79,
	0x63, 0x6c, 0x65, 0x1a, 0x36, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x86, 0x01, 0x0a, 0x0e,
	0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x22, 0x37, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x76, 0x63, 0x70, 0x75, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x22, 0x4b, 0x0a,
	0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a, 0x05,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x65,
	0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x6c,
	0x6c, 0x6f, 0x77, 0x52, 0x05, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x22, 0x36, 0x0a, 0x0c, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x22, 0x6c, 0x0a, 0x09, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x31, 0x0a,
	0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x22, 0x4d, 0x0a, 0x09, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x69, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x61, 0x69, 0x6c, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x40, 0x0a, 0x12, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x2c, 0x0a, 0x0b,
	0x57, 0x61, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x22, 0x73, 0x0a, 0x0c, 0x57, 0x61,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68,
	0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x22,
	0x51, 0x0a, 0x0b, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x67, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x67, 0x72, 0x61, 0x63, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x2e, 0x0a, 0x0d, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x49, 0x64, 0x22, 0xb6, 0x01, 0x0a, 0x0e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x19,
	0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x78,
	0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x16, 0x0a,
	0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05,
	0x73, 0x74, 0x64, 0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x09, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x5f, 0x65,
	0x6f, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x73, 0x74, 0x64, 0x69,
	0x6e, 0x45, 0x6f, 0x66, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x4b, 0x0a, 0x10, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x90, 0x01, 0x0a,
	0x1a, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45,
	0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x65,
	0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x78,
	0x65, 0x63, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x65, 0x78, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x45, 0x78, 0x69, 0x74, 0x48, 0x00, 0x52, 0x04, 0x65,
	0x78, 0x69, 0x74, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x3f, 0x0a, 0x11, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x22, 0x82, 0x02, 0x0a, 0x0f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x65, 0x63,
	0x45, 0x78, 0x69, 0x74, 0x12, 0x38, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x45, 0x78, 0x69, 0x74, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7e, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x45, 0x58, 0x49, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x41, 0x4e, 0x44, 0x42, 0x4f, 0x58, 0x5f, 0x47, 0x4f, 0x4e,
	0x45, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x54, 0x52,
	0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03,
	0x12, 0x13, 0x0a, 0x0f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45,
	0x4c, 0x45, 0x44, 0x10, 0x04, 0x22, 0xf2, 0x01, 0x0a, 0x0d, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65,
	0x2e, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x61, 0x73, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x52, 0x45, 0x41, 0x53,
	0x4f, 0x4e, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46,
	0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e,
	0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x18, 0x0a, 0x14, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x41,
	0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x1e, 0x0a, 0x1a, 0x52, 0x45,
	0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x4f, 0x54,
	0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x32, 0x9a, 0x03, 0x0a, 0x0e, 0x53,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a,
	0x06, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x12, 0x17, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x61, 0x75, 0x6e,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x35, 0x0a, 0x04, 0x57, 0x61, 0x69, 0x74, 0x12, 0x15, 0x2e,
	0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x57, 0x61, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x04,
	0x4b, 0x69, 0x6c, 0x6c, 0x12, 0x15, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x65,
	0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x12, 0x17, 0x2e,
	0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x55, 0x0a, 0x04, 0x45, 0x78, 0x65, 0x63, 0x12, 0x23, 0x2e, 0x73, 0x65, 0x74, 0x65, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x73, 0x65, 0x74, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x65, 0x72, 0x6f, 0x72, 0x6f, 0x6f, 0x74, 0x2d, 0x61,
	0x69, 0x2f, 0x73, 0x65, 0x74, 0x65, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x76, 0x31, 0x3b, 0x73, 0x65, 0x74, 0x65, 0x63, 0x76, 0x31, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_api_grpc_v1_sandbox_proto_rawDescOnce sync.Once
	file_api_grpc_v1_sandbox_proto_rawDescData []byte
)

func file_api_grpc_v1_sandbox_proto_rawDescGZIP() []byte {
	file_api_grpc_v1_sandbox_proto_rawDescOnce.Do(func() {
		file_api_grpc_v1_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_v1_sandbox_proto_rawDesc), len(file_api_grpc_v1_sandbox_proto_rawDesc)))
	})
	return file_api_grpc_v1_sandbox_proto_rawDescData
}

var file_api_grpc_v1_sandbox_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_grpc_v1_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_grpc_v1_sandbox_proto_goTypes = []any{
	(SessionExecExit_Status)(0),        // 0: setec.v1.SessionExecExit.Status
	(AttachFailure_Reason)(0),          // 1: setec.v1.AttachFailure.Reason
	(*LaunchRequest)(nil),              // 2: setec.v1.LaunchRequest
	(*LaunchResponse)(nil),             // 3: setec.v1.LaunchResponse
	(*Resources)(nil),                  // 4: setec.v1.Resources
	(*Network)(nil),                    // 5: setec.v1.Network
	(*NetworkAllow)(nil),               // 6: setec.v1.NetworkAllow
	(*Lifecycle)(nil),                  // 7: setec.v1.Lifecycle
	(*Workspace)(nil),                  // 8: setec.v1.Workspace
	(*StreamLogsRequest)(nil),          // 9: setec.v1.StreamLogsRequest
	(*StreamLogsResponse)(nil),         // 10: setec.v1.StreamLogsResponse
	(*WaitRequest)(nil),                // 11: setec.v1.WaitRequest
	(*WaitResponse)(nil),               // 12: setec.v1.WaitResponse
	(*KillRequest)(nil),                // 13: setec.v1.KillRequest
	(*KillResponse)(nil),               // 14: setec.v1.KillResponse
	(*AttachRequest)(nil),              // 15: setec.v1.AttachRequest
	(*AttachResponse)(nil),             // 16: setec.v1.AttachResponse
	(*SandboxServiceExecRequest)(nil),  // 17: setec.v1.SandboxServiceExecRequest
	(*SessionExecStart)(nil),           // 18: setec.v1.SessionExecStart
	(*SandboxServiceExecResponse)(nil), // 19: setec.v1.SandboxServiceExecResponse
	(*SessionExecOutput)(nil),          // 20: setec.v1.SessionExecOutput
	(*SessionExecExit)(nil),            // 21: setec.v1.SessionExecExit
	(*AttachFailure)(nil),              // 22: setec.v1.AttachFailure
	nil,                                // 23: setec.v1.LaunchRequest.EnvEntry
}
var file_api_grpc_v1_sandbox_proto_depIdxs = []int32{
	23, // 0: setec.v1.LaunchRequest.env:type_name -> setec.v1.LaunchRequest.EnvEntry
	4,  // 1: setec.v1.LaunchRequest.resources:type_name -> setec.v1.Resources
	5,  // 2: setec.v1.LaunchRequest.network:type_name -> setec.v1.Network
	7,  // 3: setec.v1.LaunchRequest.lifecycle:type_name -> setec.v1.Lifecycle
	6,  // 4: setec.v1.Network.allow:type_name -> setec.v1.NetworkAllow
	8,  // 5: setec.v1.Lifecycle.workspace:type_name -> setec.v1.Workspace
	18, // 6: setec.v1.SandboxServiceExecRequest.start:type_name -> setec.v1.SessionExecStart
	20, // 7: setec.v1.SandboxServiceExecResponse.output:type_name -> setec.v1.SessionExecOutput
	21, // 8: setec.v1.SandboxServiceExecResponse.exit:type_name -> setec.v1.SessionExecExit
	0,  // 9: setec.v1.SessionExecExit.status:type_name -> setec.v1.SessionExecExit.Status
	1,  // 10: setec.v1.AttachFailure.reason:type_name -> setec.v1.AttachFailure.Reason
	2,  // 11: setec.v1.SandboxService.Launch:input_type -> setec.v1.LaunchRequest
	9,  // 12: setec.v1.SandboxService.StreamLogs:input_type -> setec.v1.StreamLogsRequest
	11, // 13: setec.v1.SandboxService.Wait:input_type -> setec.v1.WaitRequest
	13, // 14: setec.v1.SandboxService.Kill:input_type -> setec.v1.KillRequest
	15, // 15: setec.v1.SandboxService.Attach:input_type -> setec.v1.AttachRequest
	17, // 16: setec.v1.SandboxService.Exec:input_type -> setec.v1.SandboxServiceExecRequest
	3,  // 17: setec.v1.SandboxService.Launch:output_type -> setec.v1.LaunchResponse
	10, // 18: setec.v1.SandboxService.StreamLogs:output_type -> setec.v1.StreamLogsResponse
	12, // 19: setec.v1.SandboxService.Wait:output_type -> setec.v1.WaitResponse
	14, // 20: setec.v1.SandboxService.Kill:output_type -> setec.v1.KillResponse
	16, // 21: setec.v1.SandboxService.Attach:output_type -> setec.v1.AttachResponse
	19, // 22: setec.v1.SandboxService.Exec:output_type -> setec.v1.SandboxServiceExecResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_grpc_v1_sandbox_proto_init() }
func file_api_grpc_v1_sandbox_proto_init() {
	if File_api_grpc_v1_sandbox_proto != nil {
		return
	}
	file_api_grpc_v1_sandbox_proto_msgTypes[15].OneofWrappers = []any{
		(*SandboxServiceExecRequest_Start)(nil),
		(*SandboxServiceExecRequest_Stdin)(nil),
		(*SandboxServiceExecRequest_StdinEof)(nil),
	}
	file_api_grpc_v1_sandbox_proto_msgTypes[17].OneofWrappers = []any{
		(*SandboxServiceExecResponse_Output)(nil),
		(*SandboxServiceExecResponse_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_v1_sandbox_proto_rawDesc), len(file_api_grpc_v1_sandbox_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_v1_sandbox_proto_goTypes,
		DependencyIndexes: file_api_grpc_v1_sandbox_proto_depIdxs,
		EnumInfos:         file_api_grpc_v1_sandbox_proto_enumTypes,
		MessageInfos:      file_api_grpc_v1_sandbox_proto_msgTypes,
	}.Build()
	File_api_grpc_v1_sandbox_proto = out.File
	file_api_grpc_v1_sandbox_proto_goTypes = nil
	file_api_grpc_v1_sandbox_proto_depIdxs = nil
}
