// Copyright 2026 The Setec Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/grpc/v1/sandbox.proto

package setecv1grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxService_Launch_FullMethodName                = "/setec.v1.SandboxService/Launch"
	SandboxService_StreamLogs_FullMethodName            = "/setec.v1.SandboxService/StreamLogs"
	SandboxService_Wait_FullMethodName                  = "/setec.v1.SandboxService/Wait"
	SandboxService_Kill_FullMethodName                  = "/setec.v1.SandboxService/Kill"
	SandboxService_Suspend_FullMethodName               = "/setec.v1.SandboxService/Suspend"
	SandboxService_Resume_FullMethodName                = "/setec.v1.SandboxService/Resume"
	SandboxService_Fork_FullMethodName                  = "/setec.v1.SandboxService/Fork"
	SandboxService_Snapshot_FullMethodName              = "/setec.v1.SandboxService/Snapshot"
	SandboxService_Keep_FullMethodName                  = "/setec.v1.SandboxService/Keep"
	SandboxService_Pin_FullMethodName                   = "/setec.v1.SandboxService/Pin"
	SandboxService_VerifySandboxIdentity_FullMethodName = "/setec.v1.SandboxService/VerifySandboxIdentity"
	SandboxService_Attach_FullMethodName                = "/setec.v1.SandboxService/Attach"
	SandboxService_Exec_FullMethodName                  = "/setec.v1.SandboxService/Exec"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SandboxService is the gRPC frontend for launching and observing Setec
// Sandboxes. Every hop uses mTLS (docs/design/threat-model.md). The client certificate names
// the caller and carries no tenancy: tenant data isolation is the job of
// the caller, and the job of Setec is the isolation of untrusted code
// (docs/design/threat-model.md). The frontend translates these RPCs to Sandbox
// CR CRUD; all cluster-side policy — SandboxClass constraints,
// ResourceQuota, NetworkPolicy — applies identically to direct CR
// consumers and frontend clients.
//
// This is the stable v1 (setec.v1) isolation ABI. It is a general-purpose
// microVM isolation surface and carries NO datastore, workspace-binding,
// or zeroroot-platform coupling: Setec is a standalone OSS sandbox runtime
// and holds no data plane. The surface is WIRE-stable — guarded
// by `buf breaking` (WIRE) in CI — so existing wire encodings remain
// compatible across releases.
type SandboxServiceClient interface {
	// Launch creates a Sandbox CR in the caller's tenant namespace and
	// returns a sandbox id the caller can use for subsequent operations.
	Launch(ctx context.Context, in *LaunchRequest, opts ...grpc.CallOption) (*LaunchResponse, error)
	// StreamLogs streams the Sandbox's backing Pod logs. Terminates when
	// the Pod terminates (or follow=false and the Pod is already terminal).
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamLogsResponse], error)
	// Wait blocks until the Sandbox reaches a terminal phase and returns
	// its exit code and reason. A previously-terminated Sandbox returns
	// immediately.
	Wait(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*WaitResponse, error)
	// Kill deletes the Sandbox CR. Owner-reference GC removes the Pod and
	// NetworkPolicy. A positive grace_seconds gives the workload that
	// long between SIGTERM and SIGKILL first.
	Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error)
	// Suspend checkpoints a session and releases its microVM. The session
	// keeps its workspace and its checkpoint, and costs no compute while it
	// is suspended (setec#193). Only a session of a class with
	// sessionCheckpoint suspends: FAILED_PRECONDITION otherwise. A suspend
	// of a suspended session succeeds.
	Suspend(ctx context.Context, in *SuspendRequest, opts ...grpc.CallOption) (*SuspendResponse, error)
	// Resume brings a suspended session back: a new microVM loads its
	// checkpoint and passes the isolation checks before the session runs.
	// An Attach or an Exec on a session that suspended for idleness resumes
	// it too. A resume of a running session succeeds.
	Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error)
	// Fork takes a snapshot of a running launcher sandbox and starts count
	// sandboxes from it (setec#195). Each fork gets a new identity, new
	// randomness and its own writable layer, and the network that this
	// request gives, never the network of the source. Only the owner of
	// the source can fork it. The snapshot is deleted after
	// snapshot_ttl_seconds once no fork still needs it.
	Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*ForkResponse, error)
	// Snapshot takes a full snapshot of a running launcher sandbox and
	// returns its name (setec#242). The snapshot belongs to the pair of
	// client and tenant of the sandbox, outlives the sandbox, and is deleted
	// ttl_seconds after it is taken, once no sandbox still loads it. A
	// later Launch with LaunchRequest.from_snapshot starts a normal sandbox
	// from it. Only the owner of the sandbox can take it.
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// Keep takes a snapshot of a running launcher sandbox for a later
	// review (setec#196). The snapshot is sealed with the key of the
	// tenant, opens only in a review sandbox with no network (see
	// LaunchRequest.review_snapshot), and is deleted after 30 days unless
	// a person pins it.
	Keep(ctx context.Context, in *KeepRequest, opts ...grpc.CallOption) (*KeepResponse, error)
	// Pin keeps a kept snapshot past its 30 days, or lets it expire again.
	// The pinned snapshots of a tenant count against a storage limit, and a
	// pin above it is FAILED_PRECONDITION.
	Pin(ctx context.Context, in *PinRequest, opts ...grpc.CallOption) (*PinResponse, error)
	// VerifySandboxIdentity checks an identity token that a process in a
	// launcher sandbox got from the identity socket of its machine
	// (setec#235), and returns the sandbox that the token names. A verifier
	// uses it in place of a hostname or a header that the process writes.
	// The token must be signed with the key of that sandbox, be for the
	// audience of the request, be in its lifetime, and carry the current
	// identity generation of the sandbox. A token from before a snapshot,
	// which a fork finds in its copy of the memory, does not verify. Only
	// the owner of the sandbox can verify its tokens. A token that does
	// not verify is UNAUTHENTICATED.
	VerifySandboxIdentity(ctx context.Context, in *VerifySandboxIdentityRequest, opts ...grpc.CallOption) (*VerifySandboxIdentityResponse, error)
	// Attach resolves a session handle (the sandbox_id returned by
	// Launch) to its live session so a caller that disconnected — or a
	// caller talking to a restarted frontend — can reattach and continue
	// with the streaming RPCs (StreamLogs, Wait) against the same
	// running microVM. Resolution is stateless: the frontend holds no
	// session table, so the handle resolves from cluster state alone and
	// reattach works across frontend restarts by construction.
	//
	// Attach also registers caller activity for the session, which
	// exempts it from per-SandboxClass idle eviction (docs/design/lifecycles.md: a
	// session in active use is never idle-reaped).
	//
	// Failure shapes (each carries an AttachFailure detail so callers
	// can switch on reason without parsing message text):
	//   - NOT_FOUND + SESSION_NOT_FOUND: the handle resolves to no live
	//     Sandbox (never existed, already deleted, or the UID in the
	//     handle belongs to an earlier Sandbox with the same name).
	//   - FAILED_PRECONDITION + SESSION_ENDED: the Sandbox exists but
	//     the session is over (terminal phase, or teardown in progress).
	//   - FAILED_PRECONDITION + NOT_A_SESSION: the Sandbox is ephemeral;
	//     the ephemeral lifecycle has no reattach semantics (docs/design/lifecycles.md).
	Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*AttachResponse, error)
	// Exec runs a command INSIDE an existing session Sandbox's running
	// microVM and streams its stdio, so a session can be worked on
	// across many turns instead of being limited to the single
	// immutable spec.command it booted with (docs/design/lifecycles.md).
	//
	// It enters a VM that is already up, so successive commands see
	// each other's effects on the durable /workspace volume.
	//
	// Protocol: the client sends exactly one SessionExecStart as the
	// FIRST message, then zero or more stdin chunks, then optionally
	// stdin_eof. The server streams SessionExecOutput messages and
	// terminates the stream with EXACTLY ONE SessionExecExit.
	//
	// Exit reporting is definitive by construction. The caller must
	// never infer success from a closed stream: SessionExecExit.status
	// is the discriminator, and only STATUS_EXITED means exit_code is
	// meaningful. When the command's fate cannot be established — the
	// microVM vanished mid-exec, the node drained, the transport broke
	// — the server still sends a SessionExecExit carrying the
	// corresponding non-EXITED status instead of a fabricated code. A
	// stream that ends with no SessionExecExit at all is an abnormal
	// termination and the command MUST be treated as of unknown
	// outcome; it is never success and never a specific exit code.
	//
	// The command runs rooted at the session's durable /workspace (the
	// session container's working directory), as the same unprivileged
	// user, with the same capabilities and seccomp profile as the
	// booted workload: Exec is not an escalation path, it is a second
	// process inside the same isolation boundary.
	//
	// An in-flight Exec registers as session activity for the whole of
	// its run, so a long build can never be idle-evicted underneath the
	// caller (docs/design/lifecycles.md).
	//
	// A session whose VM is paused or suspended is resumed first and
	// the command runs once it is back (docs/design/lifecycles.md suspend/resume); the
	// caller sees only the added latency.
	//
	// Failure shapes (each carries an AttachFailure detail, the same
	// typed session-handle resolution detail Attach returns, so a
	// caller switches on one reason enum for both verbs):
	//   - NOT_FOUND + SESSION_NOT_FOUND: the handle resolves to no live
	//     Sandbox.
	//   - FAILED_PRECONDITION + SESSION_ENDED: the session is over.
	//   - FAILED_PRECONDITION + NOT_A_SESSION: the Sandbox is
	//     ephemeral; its one command is its whole life (docs/design/lifecycles.md).
	//   - FAILED_PRECONDITION + SESSION_NOT_RUNNING: the session could
	//     not be brought to a running microVM in time.
	// These are RPC-level errors raised before the command starts, so
	// no SessionExecExit is sent and no command ran. Once the stream is
	// established, every outcome is reported as a SessionExecExit instead.
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SandboxServiceExecRequest, SandboxServiceExecResponse], error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) Launch(ctx context.Context, in *LaunchRequest, opts ...grpc.CallOption) (*LaunchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaunchResponse)
	err := c.cc.Invoke(ctx, SandboxService_Launch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxService_ServiceDesc.Streams[0], SandboxService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, StreamLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_StreamLogsClient = grpc.ServerStreamingClient[StreamLogsResponse]

func (c *sandboxServiceClient) Wait(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*WaitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitResponse)
	err := c.cc.Invoke(ctx, SandboxService_Wait_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillResponse)
	err := c.cc.Invoke(ctx, SandboxService_Kill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Suspend(ctx context.Context, in *SuspendRequest, opts ...grpc.CallOption) (*SuspendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendResponse)
	err := c.cc.Invoke(ctx, SandboxService_Suspend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeResponse)
	err := c.cc.Invoke(ctx, SandboxService_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*ForkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForkResponse)
	err := c.cc.Invoke(ctx, SandboxService_Fork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, SandboxService_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Keep(ctx context.Context, in *KeepRequest, opts ...grpc.CallOption) (*KeepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeepResponse)
	err := c.cc.Invoke(ctx, SandboxService_Keep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Pin(ctx context.Context, in *PinRequest, opts ...grpc.CallOption) (*PinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PinResponse)
	err := c.cc.Invoke(ctx, SandboxService_Pin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) VerifySandboxIdentity(ctx context.Context, in *VerifySandboxIdentityRequest, opts ...grpc.CallOption) (*VerifySandboxIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySandboxIdentityResponse)
	err := c.cc.Invoke(ctx, SandboxService_VerifySandboxIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*AttachResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachResponse)
	err := c.cc.Invoke(ctx, SandboxService_Attach_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SandboxServiceExecRequest, SandboxServiceExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxService_ServiceDesc.Streams[1], SandboxService_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SandboxServiceExecRequest, SandboxServiceExecResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_ExecClient = grpc.BidiStreamingClient[SandboxServiceExecRequest, SandboxServiceExecResponse]

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility.
//
// SandboxService is the gRPC frontend for launching and observing Setec
// Sandboxes. Every hop uses mTLS (docs/design/threat-model.md). The client certificate names
// the caller and carries no tenancy: tenant data isolation is the job of
// the caller, and the job of Setec is the isolation of untrusted code
// (docs/design/threat-model.md). The frontend translates these RPCs to Sandbox
// CR CRUD; all cluster-side policy — SandboxClass constraints,
// ResourceQuota, NetworkPolicy — applies identically to direct CR
// consumers and frontend clients.
//
// This is the stable v1 (setec.v1) isolation ABI. It is a general-purpose
// microVM isolation surface and carries NO datastore, workspace-binding,
// or zeroroot-platform coupling: Setec is a standalone OSS sandbox runtime
// and holds no data plane. The surface is WIRE-stable — guarded
// by `buf breaking` (WIRE) in CI — so existing wire encodings remain
// compatible across releases.
type SandboxServiceServer interface {
	// Launch creates a Sandbox CR in the caller's tenant namespace and
	// returns a sandbox id the caller can use for subsequent operations.
	Launch(context.Context, *LaunchRequest) (*LaunchResponse, error)
	// StreamLogs streams the Sandbox's backing Pod logs. Terminates when
	// the Pod terminates (or follow=false and the Pod is already terminal).
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[StreamLogsResponse]) error
	// Wait blocks until the Sandbox reaches a terminal phase and returns
	// its exit code and reason. A previously-terminated Sandbox returns
	// immediately.
	Wait(context.Context, *WaitRequest) (*WaitResponse, error)
	// Kill deletes the Sandbox CR. Owner-reference GC removes the Pod and
	// NetworkPolicy. A positive grace_seconds gives the workload that
	// long between SIGTERM and SIGKILL first.
	Kill(context.Context, *KillRequest) (*KillResponse, error)
	// Suspend checkpoints a session and releases its microVM. The session
	// keeps its workspace and its checkpoint, and costs no compute while it
	// is suspended (setec#193). Only a session of a class with
	// sessionCheckpoint suspends: FAILED_PRECONDITION otherwise. A suspend
	// of a suspended session succeeds.
	Suspend(context.Context, *SuspendRequest) (*SuspendResponse, error)
	// Resume brings a suspended session back: a new microVM loads its
	// checkpoint and passes the isolation checks before the session runs.
	// An Attach or an Exec on a session that suspended for idleness resumes
	// it too. A resume of a running session succeeds.
	Resume(context.Context, *ResumeRequest) (*ResumeResponse, error)
	// Fork takes a snapshot of a running launcher sandbox and starts count
	// sandboxes from it (setec#195). Each fork gets a new identity, new
	// randomness and its own writable layer, and the network that this
	// request gives, never the network of the source. Only the owner of
	// the source can fork it. The snapshot is deleted after
	// snapshot_ttl_seconds once no fork still needs it.
	Fork(context.Context, *ForkRequest) (*ForkResponse, error)
	// Snapshot takes a full snapshot of a running launcher sandbox and
	// returns its name (setec#242). The snapshot belongs to the pair of
	// client and tenant of the sandbox, outlives the sandbox, and is deleted
	// ttl_seconds after it is taken, once no sandbox still loads it. A
	// later Launch with LaunchRequest.from_snapshot starts a normal sandbox
	// from it. Only the owner of the sandbox can take it.
	Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	// Keep takes a snapshot of a running launcher sandbox for a later
	// review (setec#196). The snapshot is sealed with the key of the
	// tenant, opens only in a review sandbox with no network (see
	// LaunchRequest.review_snapshot), and is deleted after 30 days unless
	// a person pins it.
	Keep(context.Context, *KeepRequest) (*KeepResponse, error)
	// Pin keeps a kept snapshot past its 30 days, or lets it expire again.
	// The pinned snapshots of a tenant count against a storage limit, and a
	// pin above it is FAILED_PRECONDITION.
	Pin(context.Context, *PinRequest) (*PinResponse, error)
	// VerifySandboxIdentity checks an identity token that a process in a
	// launcher sandbox got from the identity socket of its machine
	// (setec#235), and returns the sandbox that the token names. A verifier
	// uses it in place of a hostname or a header that the process writes.
	// The token must be signed with the key of that sandbox, be for the
	// audience of the request, be in its lifetime, and carry the current
	// identity generation of the sandbox. A token from before a snapshot,
	// which a fork finds in its copy of the memory, does not verify. Only
	// the owner of the sandbox can verify its tokens. A token that does
	// not verify is UNAUTHENTICATED.
	VerifySandboxIdentity(context.Context, *VerifySandboxIdentityRequest) (*VerifySandboxIdentityResponse, error)
	// Attach resolves a session handle (the sandbox_id returned by
	// Launch) to its live session so a caller that disconnected — or a
	// caller talking to a restarted frontend — can reattach and continue
	// with the streaming RPCs (StreamLogs, Wait) against the same
	// running microVM. Resolution is stateless: the frontend holds no
	// session table, so the handle resolves from cluster state alone and
	// reattach works across frontend restarts by construction.
	//
	// Attach also registers caller activity for the session, which
	// exempts it from per-SandboxClass idle eviction (docs/design/lifecycles.md: a
	// session in active use is never idle-reaped).
	//
	// Failure shapes (each carries an AttachFailure detail so callers
	// can switch on reason without parsing message text):
	//   - NOT_FOUND + SESSION_NOT_FOUND: the handle resolves to no live
	//     Sandbox (never existed, already deleted, or the UID in the
	//     handle belongs to an earlier Sandbox with the same name).
	//   - FAILED_PRECONDITION + SESSION_ENDED: the Sandbox exists but
	//     the session is over (terminal phase, or teardown in progress).
	//   - FAILED_PRECONDITION + NOT_A_SESSION: the Sandbox is ephemeral;
	//     the ephemeral lifecycle has no reattach semantics (docs/design/lifecycles.md).
	Attach(context.Context, *AttachRequest) (*AttachResponse, error)
	// Exec runs a command INSIDE an existing session Sandbox's running
	// microVM and streams its stdio, so a session can be worked on
	// across many turns instead of being limited to the single
	// immutable spec.command it booted with (docs/design/lifecycles.md).
	//
	// It enters a VM that is already up, so successive commands see
	// each other's effects on the durable /workspace volume.
	//
	// Protocol: the client sends exactly one SessionExecStart as the
	// FIRST message, then zero or more stdin chunks, then optionally
	// stdin_eof. The server streams SessionExecOutput messages and
	// terminates the stream with EXACTLY ONE SessionExecExit.
	//
	// Exit reporting is definitive by construction. The caller must
	// never infer success from a closed stream: SessionExecExit.status
	// is the discriminator, and only STATUS_EXITED means exit_code is
	// meaningful. When the command's fate cannot be established — the
	// microVM vanished mid-exec, the node drained, the transport broke
	// — the server still sends a SessionExecExit carrying the
	// corresponding non-EXITED status instead of a fabricated code. A
	// stream that ends with no SessionExecExit at all is an abnormal
	// termination and the command MUST be treated as of unknown
	// outcome; it is never success and never a specific exit code.
	//
	// The command runs rooted at the session's durable /workspace (the
	// session container's working directory), as the same unprivileged
	// user, with the same capabilities and seccomp profile as the
	// booted workload: Exec is not an escalation path, it is a second
	// process inside the same isolation boundary.
	//
	// An in-flight Exec registers as session activity for the whole of
	// its run, so a long build can never be idle-evicted underneath the
	// caller (docs/design/lifecycles.md).
	//
	// A session whose VM is paused or suspended is resumed first and
	// the command runs once it is back (docs/design/lifecycles.md suspend/resume); the
	// caller sees only the added latency.
	//
	// Failure shapes (each carries an AttachFailure detail, the same
	// typed session-handle resolution detail Attach returns, so a
	// caller switches on one reason enum for both verbs):
	//   - NOT_FOUND + SESSION_NOT_FOUND: the handle resolves to no live
	//     Sandbox.
	//   - FAILED_PRECONDITION + SESSION_ENDED: the session is over.
	//   - FAILED_PRECONDITION + NOT_A_SESSION: the Sandbox is
	//     ephemeral; its one command is its whole life (docs/design/lifecycles.md).
	//   - FAILED_PRECONDITION + SESSION_NOT_RUNNING: the session could
	//     not be brought to a running microVM in time.
	// These are RPC-level errors raised before the command starts, so
	// no SessionExecExit is sent and no command ran. Once the stream is
	// established, every outcome is reported as a SessionExecExit instead.
	Exec(grpc.BidiStreamingServer[SandboxServiceExecRequest, SandboxServiceExecResponse]) error
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServiceServer struct{}

func (UnimplementedSandboxServiceServer) Launch(context.Context, *LaunchRequest) (*LaunchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Launch not implemented")
}
func (UnimplementedSandboxServiceServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[StreamLogsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedSandboxServiceServer) Wait(context.Context, *WaitRequest) (*WaitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Wait not implemented")
}
func (UnimplementedSandboxServiceServer) Kill(context.Context, *KillRequest) (*KillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Kill not implemented")
}
func (UnimplementedSandboxServiceServer) Suspend(context.Context, *SuspendRequest) (*SuspendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Suspend not implemented")
}
func (UnimplementedSandboxServiceServer) Resume(context.Context, *ResumeRequest) (*ResumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedSandboxServiceServer) Fork(context.Context, *ForkRequest) (*ForkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fork not implemented")
}
func (UnimplementedSandboxServiceServer) Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedSandboxServiceServer) Keep(context.Context, *KeepRequest) (*KeepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Keep not implemented")
}
func (UnimplementedSandboxServiceServer) Pin(context.Context, *PinRequest) (*PinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pin not implemented")
}
func (UnimplementedSandboxServiceServer) VerifySandboxIdentity(context.Context, *VerifySandboxIdentityRequest) (*VerifySandboxIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifySandboxIdentity not implemented")
}
func (UnimplementedSandboxServiceServer) Attach(context.Context, *AttachRequest) (*AttachResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedSandboxServiceServer) Exec(grpc.BidiStreamingServer[SandboxServiceExecRequest, SandboxServiceExecResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}
func (UnimplementedSandboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	// If the following call pancis, it indicates UnimplementedSandboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_Launch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Launch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Launch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Launch(ctx, req.(*LaunchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServiceServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, StreamLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_StreamLogsServer = grpc.ServerStreamingServer[StreamLogsResponse]

func _SandboxService_Wait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Wait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Wait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Wait(ctx, req.(*WaitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Kill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Kill(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Suspend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Suspend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Suspend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Suspend(ctx, req.(*SuspendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Resume(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Fork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Fork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Fork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Fork(ctx, req.(*ForkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Keep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Keep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Keep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Keep(ctx, req.(*KeepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Pin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Pin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Pin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Pin(ctx, req.(*PinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_VerifySandboxIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySandboxIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).VerifySandboxIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_VerifySandboxIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).VerifySandboxIdentity(ctx, req.(*VerifySandboxIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Attach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Attach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Attach_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Attach(ctx, req.(*AttachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SandboxServiceServer).Exec(&grpc.GenericServerStream[SandboxServiceExecRequest, SandboxServiceExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_ExecServer = grpc.BidiStreamingServer[SandboxServiceExecRequest, SandboxServiceExecResponse]

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "setec.v1.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Launch",
			Handler:    _SandboxService_Launch_Handler,
		},
		{
			MethodName: "Wait",
			Handler:    _SandboxService_Wait_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _SandboxService_Kill_Handler,
		},
		{
			MethodName: "Suspend",
			Handler:    _SandboxService_Suspend_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _SandboxService_Resume_Handler,
		},
		{
			MethodName: "Fork",
			Handler:    _SandboxService_Fork_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _SandboxService_Snapshot_Handler,
		},
		{
			MethodName: "Keep",
			Handler:    _SandboxService_Keep_Handler,
		},
		{
			MethodName: "Pin",
			Handler:    _SandboxService_Pin_Handler,
		},
		{
			MethodName: "VerifySandboxIdentity",
			Handler:    _SandboxService_VerifySandboxIdentity_Handler,
		},
		{
			MethodName: "Attach",
			Handler:    _SandboxService_Attach_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _SandboxService_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _SandboxService_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/grpc/v1/sandbox.proto",
}
